export const AUTHENTICATE = 'AUTHENTICATE';
export const MAIN_SELECT_TAB = 'MAIN_SELECT_TAB';
export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP';

// Sidebar actions
export const SIDEBAR_CURRENT_SET_TAB_NAME = 'SIDEBAR_CURRENT_SET_TAB_NAME';

// Modal actions
export const MODAL_OPEN_ADD_APPEARANCE_TO_SIMILAR_FRAMES = 'MODAL_OPEN_ADD_APPEARANCE_TO_SIMILAR_FRAMES';
export const MODAL_OPEN_CREATE_CHARACTER_MARKER = 'MODAL_OPEN_CREATE_CHARACTER_MARKER';
export const MODAL_OPEN_CREATE_PRODUCT_MARKER = 'MODAL_OPEN_CREATE_PRODUCT_MARKER';
export const MODAL_OPEN_UPDATE_CHARACTER_MARKER = 'MODAL_OPEN_UPDATE_CHARACTER_MARKER';
export const MODAL_OPEN_UPDATE_PRODUCT_MARKER = 'MODAL_OPEN_UPDATE_PRODUCT_MARKER';
export const MODAL_OPEN_WHAT_TO_TAG = 'MODAL_OPEN_WHAT_TO_TAG';
export const MODAL_CLOSE = 'MODAL_CLOSE';

// Marker selection
export const APPEARANCE_HOVER = 'APPEARANCE_HOVER';
export const APPEARANCE_LEAVE = 'APPEARANCE_LEAVE';
export const APPEARANCE_TOGGLE_SELECT = 'APPEARANCE_TOGGLE_SELECT';
export const APPEARANCE_SELECT = 'APPEARANCE_SELECT';

// Visual feedback by toasts
export const TOAST_POP = 'TOAST_POP';

// Fetch a medium to show in the header
export const MEDIUM_FETCH_START = 'MEDIUM_FETCH_START';
export const MEDIUM_FETCH_SUCCESS = 'MEDIUM_FETCH_SUCCESS';
export const MEDIUM_FETCH_ERROR = 'MEDIUM_FETCH_ERROR';

// Combined action which selects a video (and the first scene)
export const VIDEO_SELECT_START = 'VIDEO_SELECT_START';
export const VIDEO_SELECT_SUCCESS = 'VIDEO_SELECT_SUCCESS';
export const VIDEO_SELECT_ERROR = 'VIDEO_SELECT_ERROR';
// Fetch a video
export const VIDEO_FETCH_START = 'VIDEO_FETCH_START';
export const VIDEO_FETCH_SUCCESS = 'VIDEO_FETCH_SUCCESS';
export const VIDEO_FETCH_ERROR = 'VIDEO_FETCH_ERROR';

export const SCENE_UPDATE_START = 'SCENE_UPDATE_START';
export const SCENE_UPDATE_SUCCESS = 'SCENE_UPDATE_SUCCESS';
export const SCENE_UPDATE_ERROR = 'SCENE_UPDATE_ERROR';

// Combined action which selects a sene and fetches the characters and products
export const SCENE_SELECT_START = 'SCENE_SELECT_START';
export const SCENE_SELECT_SUCCESS = 'SCENE_SELECT_SUCCESS';
export const SCENE_SELECT_ERROR = 'SCENE_SELECT_ERROR';
// Select the current scene
export const CURRENT_SCENE_UPDATE = 'CURRENT_SCENE_UPDATE';
// Fetching the characters on a scene
export const CHARACTERS_OF_SCENE_FETCH_START = 'CHARACTERS_OF_SCENE_FETCH_START';
export const CHARACTERS_OF_SCENE_FETCH_SUCCESS = 'CHARACTERS_OF_SCENE_FETCH_SUCCESS';
export const CHARACTERS_OF_SCENE_FETCH_ERROR = 'CHARACTERS_OF_SCENE_FETCH_ERROR';
// Fetch a character by id
export const CHARACTER_FETCH_START = 'CHARACTER_FETCH_START';
export const CHARACTER_FETCH_SUCCESS = 'CHARACTER_FETCH_SUCCESS';
export const CHARACTER_FETCH_ERROR = 'CHARACTER_FETCH_ERROR';

export const CHARACTER_OF_SCENE_DELETE_START = 'CHARACTER_OF_SCENE_DELETE_START';
export const CHARACTER_OF_SCENE_DELETE_SUCCESS = 'CHARACTER_OF_SCENE_DELETE_SUCCESS';
export const CHARACTER_OF_SCENE_DELETE_ERROR = 'CHARACTER_OF_SCENE_DELETE_ERROR';

// Fetching the partial product of a scene
export const SCENE_PRODUCTS_FETCH_START = 'SCENE_PRODUCTS_FETCH_START';
export const SCENE_PRODUCTS_FETCH_SUCCESS = 'SCENE_PRODUCTS_FETCH_SUCCESS';
export const SCENE_PRODUCTS_FETCH_ERROR = 'SCENE_PRODUCTS_FETCH_ERROR';

export const VIDEO_PRODUCTS_FETCH_START = 'VIDEO_PRODUCTS_FETCH_START';
export const VIDEO_PRODUCTS_FETCH_SUCCESS = 'VIDEO_PRODUCTS_FETCH_SUCCESS';
export const VIDEO_PRODUCTS_FETCH_ERROR = 'VIDEO_PRODUCTS_FETCH_ERROR';

export const VIDEO_PRODUCT_PERSIST_START = 'VIDEO_PRODUCT_PERSIST_START';
export const VIDEO_PRODUCT_PERSIST_SUCCESS = 'VIDEO_PRODUCT_PERSIST_SUCCESS';
export const VIDEO_PRODUCT_PERSIST_ERROR = 'VIDEO_PRODUCT_PERSIST_ERROR';

export const VIDEO_PRODUCT_DELETE_START = 'VIDEO_PRODUCT_DELETE_START';
export const VIDEO_PRODUCT_DELETE_SUCCESS = 'VIDEO_PRODUCT_DELETE_SUCCESS';
export const VIDEO_PRODUCT_DELETE_ERROR = 'VIDEO_PRODUCT_DELETE_ERROR';

export const APPEARANCE_COPY = 'APPEARANCE_COPY';

export const PRODUCT_OF_SCENE_DELETE_START = 'PRODUCT_OF_SCENE_DELETE_START';
export const PRODUCT_OF_SCENE_DELETE_SUCCESS = 'PRODUCT_OF_SCENE_DELETE_SUCCESS';
export const PRODUCT_OF_SCENE_DELETE_ERROR = 'PRODUCT_OF_SCENE_DELETE_ERROR';

// Fetch a product by id
export const PRODUCT_FETCH_START = 'PRODUCT_FETCH_START';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_ERROR = 'PRODUCT_FETCH_ERROR';

export const SIMILAR_PRODUCTS_FETCH_START = 'SIMILAR_PRODUCTS_FETCH_START';
export const SIMILAR_PRODUCTS_FETCH_SUCCESS = 'SIMILAR_PRODUCTS_FETCH_SUCCESS';
export const SIMILAR_PRODUCTS_FETCH_ERROR = 'SIMILAR_PRODUCTS_FETCH_ERROR';

// Create product marker
export const CREATE_PRODUCT_MARKER_START = 'CREATE_PRODUCT_MARKER_START';
export const CREATE_PRODUCT_MARKER_SUCCESS = 'CREATE_PRODUCT_MARKER_SUCCESS';
export const CREATE_PRODUCT_MARKER_ERROR = 'CREATE_PRODUCT_MARKER_ERROR';
export const CREATE_PRODUCT_MARKER_CANCEL = 'CREATE_PRODUCT_MARKER_CANCEL';

// Update product marker
export const UPDATE_PRODUCT_MARKER_START = 'UPDATE_PRODUCT_MARKER_START';
export const UPDATE_PRODUCT_MARKER_SUCCESS = 'UPDATE_PRODUCT_MARKER_SUCCESS';
export const UPDATE_PRODUCT_MARKER_ERROR = 'UPDATE_PRODUCT_MARKER_ERROR';
export const UPDATE_PRODUCT_MARKER_CANCEL = 'UPDATE_PRODUCT_MARKER_CANCEL';

export const UPDATE_CHARACTER_MARKER_START = 'UPDATE_CHARACTER_MARKER_START';
export const UPDATE_CHARACTER_MARKER_SUCCESS = 'UPDATE_CHARACTER_MARKER_SUCCESS';
export const UPDATE_CHARACTER_MARKER_ERROR = 'UPDATE_CHARACTER_MARKER_ERROR';

export const SEARCH_CHARACTERS_START = 'SEARCH_CHARACTERS_START';
export const SEARCH_CHARACTERS_SUCCESS = 'SEARCH_CHARACTERS_SUCCESS';
export const SEARCH_CHARACTERS_ERROR = 'SEARCH_CHARACTERS_ERROR';

export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';

export const SEARCH_GLOBAL_PRODUCTS_START = 'SEARCH_GLOBAL_PRODUCTS_START';
export const SEARCH_GLOBAL_PRODUCTS_SUCCESS = 'SEARCH_GLOBAL_PRODUCTS_SUCCESS';
export const SEARCH_GLOBAL_PRODUCTS_ERROR = 'SEARCH_GLOBAL_PRODUCTS_ERROR';

export const SUGGEST_PRODUCTS_START = 'SUGGEST_PRODUCTS_START';
export const SUGGEST_PRODUCTS_SUCCESS = 'SUGGEST_PRODUCTS_SUCCESS';
export const SUGGEST_PRODUCTS_ERROR = 'SUGGEST_PRODUCTS_ERROR';
export const CLEAR_PRODUCT_SUGGESTIONS = 'CLEAR_PRODUCT_SUGGESTIONS';

export const BRAND_FETCH_START = 'BRAND_FETCH_START';
export const BRAND_FETCH_SUCCESS = 'BRAND_FETCH_SUCCESS';
export const BRAND_FETCH_ERROR = 'BRAND_FETCH_ERROR';

// Create character marker
export const CREATE_CHARACTER_MARKER_START = 'CREATE_CHARACTER_MARKER_START';
export const CREATE_CHARACTER_MARKER_SUCCESS = 'CREATE_CHARACTER_MARKER_SUCCESS';
export const CREATE_CHARACTER_MARKER_ERROR = 'CREATE_CHARACTER_MARKER_ERROR';
export const CREATE_CHARACTER_MARKER_CANCEL = 'CREATE_CHARACTER_MARKER_CANCEL';

export const PRODUCT_SUGGESTION_ADD_IMAGE_START = 'PRODUCT_SUGGESTION_ADD_IMAGE_START';
export const PRODUCT_SUGGESTION_ADD_IMAGE_SUCCESS = 'PRODUCT_SUGGESTION_ADD_IMAGE_SUCCESS';
export const PRODUCT_SUGGESTION_ADD_IMAGE_ERROR = 'PRODUCT_SUGGESTION_ADD_IMAGE_ERROR';

export const TOGGLE_HIDE_DIFFERENT_FRAMES = 'TOGGLE_HIDE_DIFFERENT_FRAMES';
export const TOGGLE_HIDE_HIDDEN_FRAMES = 'TOGGLE_HIDE_HIDDEN_FRAMES';

export const SELECT_SIMILAR_SCENE = 'SELECT_SIMILAR_SCENE';

export const QUICKIES_SELECT_TAB = 'QUICKIES_SELECT_TAB';

export const CHARACTER_SELECT = 'CHARACTER_SELECT';
export const CHARACTER_OPEN = 'CHARACTER_OPEN';

export const PRODUCT_GROUPS_FETCH_START = 'PRODUCT_GROUPS_FETCH_START';
export const PRODUCT_GROUPS_FETCH_SUCCESS = 'PRODUCT_GROUPS_FETCH_SUCCESS';
export const PRODUCT_GROUPS_FETCH_ERROR = 'PRODUCT_GROUPS_FETCH_ERROR';

export const PRODUCT_GROUP_FETCH_START = 'PRODUCT_GROUP_FETCH_START';
export const PRODUCT_GROUP_FETCH_SUCCESS = 'PRODUCT_GROUP_FETCH_SUCCESS';
export const PRODUCT_GROUP_FETCH_ERROR = 'PRODUCT_GROUP_FETCH_ERROR';

export const PRODUCT_GROUP_PERSIST_START = 'PRODUCT_GROUP_PERSIST_START';
export const PRODUCT_GROUP_PERSIST_SUCCESS = 'PRODUCT_GROUP_PERSIST_SUCCESS';
export const PRODUCT_GROUP_PERSIST_ERROR = 'PRODUCT_GROUP_PERSIST_ERROR';

export const PRODUCT_GROUP_DELETE_START = 'PRODUCT_GROUP_DELETE_START';
export const PRODUCT_GROUP_DELETE_SUCCESS = 'PRODUCT_GROUP_DELETE_SUCCESS';
export const PRODUCT_GROUP_DELETE_ERROR = 'PRODUCT_GROUP_DELETE_ERROR';

export const CHARACTER_PRODUCT_GROUPS_FETCH_START = 'CHARACTER_PRODUCT_GROUPS_FETCH_START';
export const CHARACTER_PRODUCT_GROUPS_FETCH_SUCCESS = 'CHARACTER_PRODUCT_GROUPS_FETCH_SUCCESS';
export const CHARACTER_PRODUCT_GROUPS_FETCH_ERROR = 'CHARACTER_PRODUCT_GROUPS_FETCH_ERROR';

export const CHARACTER_PRODUCT_GROUP_FETCH_START = 'CHARACTER_PRODUCT_GROUP_FETCH_START';
export const CHARACTER_PRODUCT_GROUP_FETCH_SUCCESS = 'CHARACTER_PRODUCT_GROUP_FETCH_SUCCESS';
export const CHARACTER_PRODUCT_GROUP_FETCH_ERROR = 'CHARACTER_PRODUCT_GROUP_FETCH_ERROR';

export const CHARACTER_PRODUCT_GROUP_PERSIST_START = 'CHARACTER_PRODUCT_GROUP_PERSIST_START';
export const CHARACTER_PRODUCT_GROUP_PERSIST_SUCCESS = 'CHARACTER_PRODUCT_GROUP_PERSIST_SUCCESS';
export const CHARACTER_PRODUCT_GROUP_PERSIST_ERROR = 'CHARACTER_PRODUCT_GROUP_PERSIST_ERROR';

export const CHARACTER_PRODUCT_GROUP_DELETE_START = 'CHARACTER_PRODUCT_GROUP_DELETE_START';
export const CHARACTER_PRODUCT_GROUP_DELETE_SUCCESS = 'CHARACTER_PRODUCT_GROUP_DELETE_SUCCESS';
export const CHARACTER_PRODUCT_GROUP_DELETE_ERROR = 'CHARACTER_PRODUCT_GROUP_DELETE_ERROR';

export const LOCAL_QUICKY_DELETE = 'LOCAL_QUICKY_DELETE';
export const EDIT_PRODUCT_GROUP_SELECT = 'EDIT_PRODUCT_GROUP_SELECT';
export const EDIT_CHARACTER_PRODUCT_GROUP_SELECT = 'EDIT_CHARACTER_PRODUCT_GROUP_SELECT';
export const PRODUCT_SELECT = 'PRODUCT_SELECT';
