import * as api from '../api/actor';
import { makeApiActionCreator } from './utils';

export const ACTOR_SEARCH_START = 'ACTOR/ACTOR_SEARCH_START';
export const ACTOR_SEARCH_SUCCESS = 'ACTOR/ACTOR_SEARCH_SUCCESS';
export const ACTOR_SEARCH_ERROR = 'ACTOR/ACTOR_SEARCH_ERROR';

export const ACTORS_FETCH_START = 'ACTOR/ACTORS_FETCH_START';
export const ACTORS_FETCH_SUCCESS = 'ACTOR/ACTORS_FETCH_SUCCESS';
export const ACTORS_FETCH_ERROR = 'ACTOR/ACTORS_FETCH_ERROR';

export const ACTOR_DELETE_START = 'ACTOR/ACTOR_DELETE_START';
export const ACTOR_DELETE_SUCCESS = 'ACTOR/ACTOR_DELETE_SUCCESS';
export const ACTOR_DELETE_ERROR = 'ACTOR/ACTOR_DELETE_ERROR';

export const ACTORS_DELETE_START = 'ACTOR/ACTORS_DELETE_START';
export const ACTORS_DELETE_SUCCESS = 'ACTOR/ACTORS_DELETE_SUCCESS';
export const ACTORS_DELETE_ERROR = 'ACTOR/ACTORS_DELETE_ERROR';

export const ACTOR_PERSIST_START = 'ACTOR/ACTOR_PERSIST_START';
export const ACTOR_PERSIST_SUCCESS = 'ACTOR/ACTOR_PERSIST_SUCCESS';
export const ACTOR_PERSIST_ERROR = 'ACTOR/ACTOR_PERSIST_ERROR';

export const deleteActors = makeApiActionCreator(api.deleteActors, ACTORS_DELETE_START, ACTORS_DELETE_SUCCESS, ACTORS_DELETE_ERROR);
export const deleteActor = makeApiActionCreator(api.deleteActor, ACTOR_DELETE_START, ACTOR_DELETE_SUCCESS, ACTOR_DELETE_ERROR);
export const fetchActors = makeApiActionCreator(api.fetchActors, ACTORS_FETCH_START, ACTORS_FETCH_SUCCESS, ACTORS_FETCH_ERROR);
export const persistActor = makeApiActionCreator(api.persistActor, ACTOR_PERSIST_START, ACTOR_PERSIST_SUCCESS, ACTOR_PERSIST_ERROR);
export const searchActors = makeApiActionCreator(api.searchActors, ACTOR_SEARCH_START, ACTOR_SEARCH_SUCCESS, ACTOR_SEARCH_ERROR);
