import { makeApiActionCreator } from './utils';
import * as availabilityApi from '../api/availability';

export const AVAILABILITY_DELETE_START = 'AVAILABILITY/AVAILABILITY_DELETE_START';
export const AVAILABILITY_DELETE_SUCCESS = 'AVAILABILITY/AVAILABILITY_DELETE_SUCCESS';
export const AVAILABILITY_DELETE_ERROR = 'AVAILABILITY/AVAILABILITY_DELETE_ERROR';

export const AVAILABILITIES_FETCH_START = 'AVAILABILITY/AVAILABILITIES_FETCH_START';
export const AVAILABILITIES_FETCH_SUCCESS = 'AVAILABILITY/AVAILABILITIES_FETCH_SUCCESS';
export const AVAILABILITIES_FETCH_ERROR = 'AVAILABILITY/AVAILABILITIES_FETCH_ERROR';

export const AVAILABILITY_PERSIST_START = 'AVAILABILITY/AVAILABILITY_PERSIST_START';
export const AVAILABILITY_PERSIST_SUCCESS = 'AVAILABILITY/AVAILABILITY_PERSIST_SUCCESS';
export const AVAILABILITY_PERSIST_ERROR = 'AVAILABILITY/AVAILABILITY_PERSIST_ERROR';

export const deleteAvailability = makeApiActionCreator(availabilityApi.deleteAvailability, AVAILABILITY_DELETE_START, AVAILABILITY_DELETE_SUCCESS, AVAILABILITY_DELETE_ERROR);
export const fetchAvailabilities = makeApiActionCreator(availabilityApi.fetchAvailabilities, AVAILABILITIES_FETCH_START, AVAILABILITIES_FETCH_SUCCESS, AVAILABILITIES_FETCH_ERROR);
export const persistAvailability = makeApiActionCreator(availabilityApi.persistAvailability, AVAILABILITY_PERSIST_START, AVAILABILITY_PERSIST_SUCCESS, AVAILABILITY_PERSIST_ERROR);
