import * as api from '../api/brand';
import { makeApiActionCreator } from './utils';

export const BRAND_SEARCH_START = 'BRAND/BRAND_SEARCH_START';
export const BRAND_SEARCH_SUCCESS = 'BRAND/BRAND_SEARCH_SUCCESS';
export const BRAND_SEARCH_ERROR = 'BRAND/BRAND_SEARCH_ERROR';

export const MEDIUM_BRAND_SEARCH_START = 'BRAND/MEDIUM_BRAND_SEARCH_START';
export const MEDIUM_BRAND_SEARCH_SUCCESS = 'BRAND/MEDIUM_BRAND_SEARCH_SUCCESS';
export const MEDIUM_BRAND_SEARCH_ERROR = 'BRAND/MEDIUM_BRAND_SEARCH_ERROR';

export const MEDIUM_BRAND_PERSIST_START = 'BRAND/MEDIUM_BRAND_PERSIST_START';
export const MEDIUM_BRAND_PERSIST_SUCCESS = 'BRAND/MEDIUM_BRAND_PERSIST_SUCCESS';
export const MEDIUM_BRAND_PERSIST_ERROR = 'BRAND/MEDIUM_BRAND_PERSIST_ERROR';

export const MEDIUM_BRAND_DELETE_START = 'BRAND/MEDIUM_BRAND_DELETE_START';
export const MEDIUM_BRAND_DELETE_SUCCESS = 'BRAND/MEDIUM_BRAND_DELETE_SUCCESS';
export const MEDIUM_BRAND_DELETE_ERROR = 'BRAND/MEDIUM_BRAND_DELETE_ERROR';

export const BRANDS_FETCH_START = 'BRAND/BRANDS_FETCH_START';
export const BRANDS_FETCH_SUCCESS = 'BRAND/BRANDS_FETCH_SUCCESS';
export const BRANDS_FETCH_ERROR = 'BRAND/BRANDS_FETCH_ERROR';

export const PRODUCTS_FETCH_START = 'BRAND/PRODUCTS_FETCH_START';
export const PRODUCTS_FETCH_SUCCESS = 'BRAND/PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_ERROR = 'BRAND/PRODUCTS_FETCH_ERROR';

export const BRAND_FETCH_START = 'BRAND/BRAND_FETCH_START';
export const BRAND_FETCH_SUCCESS = 'BRAND/BRAND_FETCH_SUCCESS';
export const BRAND_FETCH_ERROR = 'BRAND/BRAND_FETCH_ERROR';

export const BRAND_DELETE_START = 'BRAND/BRAND_DELETE_START';
export const BRAND_DELETE_SUCCESS = 'BRAND/BRAND_DELETE_SUCCESS';
export const BRAND_DELETE_ERROR = 'BRAND/BRAND_DELETE_ERROR';

export const BRANDS_DELETE_START = 'BRAND/BRANDS_DELETE_START';
export const BRANDS_DELETE_SUCCESS = 'BRAND/BRANDS_DELETE_SUCCESS';
export const BRANDS_DELETE_ERROR = 'BRAND/BRANDS_DELETE_ERROR';

export const BRAND_PERSIST_START = 'BRAND/BRAND_PERSIST_START';
export const BRAND_PERSIST_SUCCESS = 'BRAND/BRAND_PERSIST_SUCCESS';
export const BRAND_PERSIST_ERROR = 'BRAND/BRAND_PERSIST_ERROR';

export const UPLOAD_LOGO_IMAGE_START = 'BRAND/UPLOAD_LOGO_IMAGE_START';
export const UPLOAD_LOGO_IMAGE_SUCCESS = 'BRAND/UPLOAD_LOGO_IMAGE_SUCCESS';
export const UPLOAD_LOGO_IMAGE_ERROR = 'BRAND/UPLOAD_LOGO_IMAGE_ERROR';

export const UPLOAD_PROFILE_IMAGE_START = 'BRAND/UPLOAD_PROFILE_IMAGE_START';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'BRAND/UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_ERROR = 'BRAND/UPLOAD_PROFILE_IMAGE_ERROR';

export const UPLOAD_FACE_IMAGE_START = 'BRAND/UPLOAD_FACE_IMAGE_START';
export const UPLOAD_FACE_IMAGE_SUCCESS = 'BRAND/UPLOAD_FACE_IMAGE_SUCCESS';
export const UPLOAD_FACE_IMAGE_ERROR = 'BRAND/UPLOAD_FACE_IMAGE_ERROR';

export const DELETE_PROFILE_IMAGE_START = 'BRAND/DELETE_PROFILE_IMAGE_START';
export const DELETE_PROFILE_IMAGE_SUCCESS = 'BRAND/DELETE_PROFILE_IMAGE_SUCCESS';
export const DELETE_PROFILE_IMAGE_ERROR = 'BRAND/DELETE_PROFILE_IMAGE_ERROR';

export const DELETE_LOGO_IMAGE_START = 'BRAND/DELETE_LOGO_IMAGE_START';
export const DELETE_LOGO_IMAGE_SUCCESS = 'BRAND/DELETE_LOGO_IMAGE_SUCCESS';
export const DELETE_LOGO_IMAGE_ERROR = 'BRAND/DELETE_LOGO_IMAGE_ERROR';

export const deleteBrand = makeApiActionCreator(api.deleteBrand, BRAND_DELETE_START, BRAND_DELETE_SUCCESS, BRAND_DELETE_ERROR);
export const deleteBrands = makeApiActionCreator(api.deleteBrands, BRANDS_DELETE_START, BRANDS_DELETE_SUCCESS, BRANDS_DELETE_ERROR);
export const deleteLogoImage = makeApiActionCreator(api.deleteLogoImage, DELETE_LOGO_IMAGE_START, DELETE_LOGO_IMAGE_SUCCESS, DELETE_LOGO_IMAGE_ERROR);
export const deleteProfileImage = makeApiActionCreator(api.deleteProfileImage, DELETE_PROFILE_IMAGE_START, DELETE_PROFILE_IMAGE_SUCCESS, DELETE_PROFILE_IMAGE_ERROR);
export const fetchBrand = makeApiActionCreator(api.fetchBrand, BRAND_FETCH_START, BRAND_FETCH_SUCCESS, BRAND_FETCH_ERROR);
export const fetchBrands = makeApiActionCreator(api.fetchBrands, BRANDS_FETCH_START, BRANDS_FETCH_SUCCESS, BRANDS_FETCH_ERROR);
export const fetchProducts = makeApiActionCreator(api.fetchProducts, PRODUCTS_FETCH_START, PRODUCTS_FETCH_SUCCESS, PRODUCTS_FETCH_ERROR);
export const persistBrand = makeApiActionCreator(api.persistBrand, BRAND_PERSIST_START, BRAND_PERSIST_SUCCESS, BRAND_PERSIST_ERROR);
export const searchBrands = makeApiActionCreator(api.searchBrands, BRAND_SEARCH_START, BRAND_SEARCH_SUCCESS, BRAND_SEARCH_ERROR);
export const uploadLogoImage = makeApiActionCreator(api.uploadLogoImage, UPLOAD_LOGO_IMAGE_START, UPLOAD_LOGO_IMAGE_SUCCESS, UPLOAD_LOGO_IMAGE_ERROR);
export const uploadProfileImage = makeApiActionCreator(api.uploadProfileImage, UPLOAD_PROFILE_IMAGE_START, UPLOAD_PROFILE_IMAGE_SUCCESS, UPLOAD_PROFILE_IMAGE_ERROR);
export const searchMediumBrands = makeApiActionCreator(api.searchMediumBrands, MEDIUM_BRAND_SEARCH_START, MEDIUM_BRAND_SEARCH_SUCCESS, MEDIUM_BRAND_SEARCH_ERROR);
export const persistMediumBrand = makeApiActionCreator(api.persistMediumBrand, MEDIUM_BRAND_PERSIST_START, MEDIUM_BRAND_PERSIST_SUCCESS, MEDIUM_BRAND_PERSIST_ERROR);
export const deleteMediumBrand = makeApiActionCreator(api.deleteMediumBrand, MEDIUM_BRAND_DELETE_START, MEDIUM_BRAND_DELETE_SUCCESS, MEDIUM_BRAND_DELETE_ERROR);
