import { makeApiActionCreator } from './utils';
import * as api from '../api/brandDashboard';

export const EVENTS_FETCH_START = 'DATA_BRAND_DASHBOARD/EVENTS_FETCH_START';
export const EVENTS_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/EVENTS_FETCH_SUCCESS';
export const EVENTS_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/EVENTS_FETCH_ERROR';

export const KEY_METRICS_FETCH_START = 'DATA_BRAND_DASHBOARD/KEY_METRICS_FETCH_START';
export const KEY_METRICS_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/KEY_METRICS_FETCH_SUCCESS';
export const KEY_METRICS_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/KEY_METRICS_FETCH_ERROR';

export const TOP_MEDIA_FETCH_START = 'DATA_BRAND_DASHBOARD/TOP_MEDIA_FETCH_START';
export const TOP_MEDIA_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/TOP_MEDIA_FETCH_SUCCESS';
export const TOP_MEDIA_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/TOP_MEDIA_FETCH_ERROR';

export const TOP_PEOPLE_FETCH_START = 'DATA_BRAND_DASHBOARD/TOP_PEOPLE_FETCH_START';
export const TOP_PEOPLE_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/TOP_PEOPLE_FETCH_SUCCESS';
export const TOP_PEOPLE_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/TOP_PEOPLE_FETCH_ERROR';

export const AGE_DATA_FETCH_START = 'DATA_BRAND_DASHBOARD/AGE_DATA_FETCH_START';
export const AGE_DATA_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/AGE_DATA_FETCH_SUCCESS';
export const AGE_DATA_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/AGE_DATA_FETCH_ERROR';

export const GENDER_DATA_FETCH_START = 'DATA_BRAND_DASHBOARD/GENDER_DATA_FETCH_START';
export const GENDER_DATA_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/GENDER_DATA_FETCH_SUCCESS';
export const GENDER_DATA_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/GENDER_DATA_FETCH_ERROR';

export const DATE_DATA_FETCH_START = 'DATA_BRAND_DASHBOARD/DATE_DATA_FETCH_START';
export const DATE_DATA_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/DATE_DATA_FETCH_SUCCESS';
export const DATE_DATA_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/DATE_DATA_FETCH_ERROR';

export const DEMOGRAPHICS_FETCH_START = 'DATA_BRAND_DASHBOARD/DEMOGRAPHICS_FETCH_START';
export const DEMOGRAPHICS_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/DEMOGRAPHICS_FETCH_SUCCESS';
export const DEMOGRAPHICS_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/DEMOGRAPHICS_FETCH_ERROR';

export const fetchBrandDashboardEvents = makeApiActionCreator(api.fetchBrandDashboardEvents, EVENTS_FETCH_START, EVENTS_FETCH_SUCCESS, EVENTS_FETCH_ERROR);
export const fetchKeyMetrics = makeApiActionCreator(api.fetchKeyMetrics, KEY_METRICS_FETCH_START, KEY_METRICS_FETCH_SUCCESS, KEY_METRICS_FETCH_ERROR);
export const fetchTopMedia = makeApiActionCreator(api.fetchTopMedia, TOP_MEDIA_FETCH_START, TOP_MEDIA_FETCH_SUCCESS, TOP_MEDIA_FETCH_ERROR);
export const fetchTopPeople = makeApiActionCreator(api.fetchTopPeople, TOP_PEOPLE_FETCH_START, TOP_PEOPLE_FETCH_SUCCESS, TOP_PEOPLE_FETCH_ERROR);
export const fetchDemographics = makeApiActionCreator(api.fetchDemographics, DEMOGRAPHICS_FETCH_START, DEMOGRAPHICS_FETCH_SUCCESS, DEMOGRAPHICS_FETCH_ERROR);
export const fetchAgeData = makeApiActionCreator(api.fetchAgeData, AGE_DATA_FETCH_START, AGE_DATA_FETCH_SUCCESS, AGE_DATA_FETCH_ERROR);
export const fetchGenderData = makeApiActionCreator(api.fetchGenderData, GENDER_DATA_FETCH_START, GENDER_DATA_FETCH_SUCCESS, GENDER_DATA_FETCH_ERROR);
export const fetchDateData = makeApiActionCreator(api.fetchDateData, DATE_DATA_FETCH_START, DATE_DATA_FETCH_SUCCESS, DATE_DATA_FETCH_ERROR);
