import { makeApiActionCreator } from './utils';
import * as brandDashbiardApi from '../api/brandDashboard';

export const TOP_MEDIA_FETCH_START = 'DATA_BRAND_DASHBOARD/TOP_MEDIA_FETCH_START';
export const TOP_MEDIA_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/TOP_MEDIA_FETCH_SUCCESS';
export const TOP_MEDIA_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/TOP_MEDIA_FETCH_ERROR';

export const TOP_PEOPLE_FETCH_START = 'DATA_BRAND_DASHBOARD/TOP_PEOPLE_FETCH_START';
export const TOP_PEOPLE_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/TOP_PEOPLE_FETCH_SUCCESS';
export const TOP_PEOPLE_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/TOP_PEOPLE_FETCH_ERROR';

export const AGE_DATA_FETCH_START = 'DATA_BRAND_DASHBOARD/AGE_DATA_FETCH_START';
export const AGE_DATA_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/AGE_DATA_FETCH_SUCCESS';
export const AGE_DATA_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/AGE_DATA_FETCH_ERROR';

export const GENDER_DATA_FETCH_START = 'DATA_BRAND_DASHBOARD/GENDER_DATA_FETCH_START';
export const GENDER_DATA_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/GENDER_DATA_FETCH_SUCCESS';
export const GENDER_DATA_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/GENDER_DATA_FETCH_ERROR';

export const DEMOGRAPHICS_FETCH_START = 'DATA_BRAND_DASHBOARD/DEMOGRAPHICS_FETCH_START';
export const DEMOGRAPHICS_FETCH_SUCCESS = 'DATA_BRAND_DASHBOARD/DEMOGRAPHICS_FETCH_SUCCESS';
export const DEMOGRAPHICS_FETCH_ERROR = 'DATA_BRAND_DASHBOARD/DEMOGRAPHICS_FETCH_ERROR';

export const fetchTopMedia = makeApiActionCreator(brandDashbiardApi.fetchTopMedia, TOP_MEDIA_FETCH_START, TOP_MEDIA_FETCH_SUCCESS, TOP_MEDIA_FETCH_ERROR);
export const fetchTopPeople = makeApiActionCreator(brandDashbiardApi.fetchTopPeople, TOP_PEOPLE_FETCH_START, TOP_PEOPLE_FETCH_SUCCESS, TOP_PEOPLE_FETCH_ERROR);
export const fetchDemographics = makeApiActionCreator(brandDashbiardApi.fetchDemographics, DEMOGRAPHICS_FETCH_START, DEMOGRAPHICS_FETCH_SUCCESS, DEMOGRAPHICS_FETCH_ERROR);
export const fetchAgeData = makeApiActionCreator(brandDashbiardApi.fetchAgeData, AGE_DATA_FETCH_START, AGE_DATA_FETCH_SUCCESS, AGE_DATA_FETCH_ERROR);
export const fetchGenderData = makeApiActionCreator(brandDashbiardApi.fetchGenderData, GENDER_DATA_FETCH_START, GENDER_DATA_FETCH_SUCCESS, GENDER_DATA_FETCH_ERROR);
