import * as api from '../api/character';
import { makeApiActionCreator } from './utils';

export const CHARACTER_SEARCH_START = 'CHARACTER/CHARACTER_SEARCH_START';
export const CHARACTER_SEARCH_SUCCESS = 'CHARACTER/CHARACTER_SEARCH_SUCCESS';
export const CHARACTER_SEARCH_ERROR = 'CHARACTER/CHARACTER_SEARCH_ERROR';

export const MEDIUM_CHARACTER_SEARCH_START = 'CHARACTER/MEDIUM_CHARACTER_SEARCH_START';
export const MEDIUM_CHARACTER_SEARCH_SUCCESS = 'CHARACTER/MEDIUM_CHARACTER_SEARCH_SUCCESS';
export const MEDIUM_CHARACTER_SEARCH_ERROR = 'CHARACTER/MEDIUM_CHARACTER_SEARCH_ERROR';

export const MEDIUM_CHARACTER_PERSIST_START = 'CHARACTER/MEDIUM_CHARACTER_PERSIST_START';
export const MEDIUM_CHARACTER_PERSIST_SUCCESS = 'CHARACTER/MEDIUM_CHARACTER_PERSIST_SUCCESS';
export const MEDIUM_CHARACTER_PERSIST_ERROR = 'CHARACTER/MEDIUM_CHARACTER_PERSIST_ERROR';

export const MEDIUM_CHARACTER_DELETE_START = 'CHARACTER/MEDIUM_CHARACTER_DELETE_START';
export const MEDIUM_CHARACTER_DELETE_SUCCESS = 'CHARACTER/MEDIUM_CHARACTER_DELETE_SUCCESS';
export const MEDIUM_CHARACTER_DELETE_ERROR = 'CHARACTER/MEDIUM_CHARACTER_DELETE_ERROR';

export const searchCharacters = makeApiActionCreator(api.searchCharacters, CHARACTER_SEARCH_START, CHARACTER_SEARCH_SUCCESS, CHARACTER_SEARCH_ERROR);
export const searchMediumCharacters = makeApiActionCreator(api.searchMediumCharacters, MEDIUM_CHARACTER_SEARCH_START, MEDIUM_CHARACTER_SEARCH_SUCCESS, MEDIUM_CHARACTER_SEARCH_ERROR);
export const persistMediumCharacter = makeApiActionCreator(api.persistMediumCharacter, MEDIUM_CHARACTER_PERSIST_START, MEDIUM_CHARACTER_PERSIST_SUCCESS, MEDIUM_CHARACTER_PERSIST_ERROR);
export const deleteMediumCharacter = makeApiActionCreator(api.deleteMediumCharacter, MEDIUM_CHARACTER_DELETE_START, MEDIUM_CHARACTER_DELETE_SUCCESS, MEDIUM_CHARACTER_DELETE_ERROR);
