import * as api from '../api/collection';
import { makeApiActionCreator } from './utils';

export const MEDIUM_COLLECTIONS_FETCH_START = 'COLLECTION/MEDIUM_COLLECTIONS_FETCH_START';
export const MEDIUM_COLLECTIONS_FETCH_SUCCESS = 'COLLECTION/MEDIUM_COLLECTIONS_FETCH_SUCCESS';
export const MEDIUM_COLLECTIONS_FETCH_ERROR = 'COLLECTION/MEDIUM_COLLECTIONS_FETCH_ERROR';

export const COLLECTION_FETCH_START = 'COLLECTION/COLLECTION_FETCH_START';
export const COLLECTION_FETCH_SUCCESS = 'COLLECTION/COLLECTION_FETCH_SUCCESS';
export const COLLECTION_FETCH_ERROR = 'COLLECTION/COLLECTION_FETCH_ERROR';

export const COLLECTION_PERSIST_START = 'COLLECTION/COLLECTION_PERSIST_START';
export const COLLECTION_PERSIST_SUCCESS = 'COLLECTION/COLLECTION_PERSIST_SUCCESS';
export const COLLECTION_PERSIST_ERROR = 'COLLECTION/COLLECTION_PERSIST_ERROR';

export const COLLECTION_DELETE_START = 'COLLECTION/COLLECTION_DELETE_START';
export const COLLECTION_DELETE_SUCCESS = 'COLLECTION/COLLECTION_DELETE_SUCCESS';
export const COLLECTION_DELETE_ERROR = 'COLLECTION/COLLECTION_DELETE_ERROR';

export const MOVE_COLLECTION_START = 'COLLECTION/MOVE_COLLECTION_START';
export const MOVE_COLLECTION_SUCCESS = 'COLLECTION/MOVE_COLLECTION_SUCCESS';
export const MOVE_COLLECTION_ERROR = 'COLLECTION/MOVE_COLLECTION_ERROR';

export const REORDER_COLLECTIONS_START = 'COLLECTION/REORDER_COLLECTIONS_START';
export const REORDER_COLLECTIONS_SUCCESS = 'COLLECTION/REORDER_COLLECTIONS_SUCCESS';
export const REORDER_COLLECTIONS_ERROR = 'COLLECTION/REORDER_COLLECTIONS_ERROR';

export const fetchMediumCollections = makeApiActionCreator(api.fetchMediumCollections, MEDIUM_COLLECTIONS_FETCH_START, MEDIUM_COLLECTIONS_FETCH_SUCCESS, MEDIUM_COLLECTIONS_FETCH_ERROR);
export const fetchCollection = makeApiActionCreator(api.fetchCollection, COLLECTION_FETCH_START, COLLECTION_FETCH_SUCCESS, COLLECTION_FETCH_ERROR);
export const persistCollection = makeApiActionCreator(api.persistCollection, COLLECTION_PERSIST_START, COLLECTION_PERSIST_SUCCESS, COLLECTION_PERSIST_ERROR);
export const deleteCollection = makeApiActionCreator(api.deleteCollection, COLLECTION_DELETE_START, COLLECTION_DELETE_SUCCESS, COLLECTION_DELETE_ERROR);
export const moveCollection = makeApiActionCreator(api.moveCollection, MOVE_COLLECTION_START, MOVE_COLLECTION_SUCCESS, MOVE_COLLECTION_ERROR);
export const reorderCollections = makeApiActionCreator(api.reorderCollections, REORDER_COLLECTIONS_START, REORDER_COLLECTIONS_SUCCESS, REORDER_COLLECTIONS_ERROR);
