import * as api from '../api/collection';
import { makeApiActionCreator } from './utils';

export const MEDIUM_COLLECTIONS_FETCH_START = 'COLLECTION/MEDIUM_COLLECTIONS_FETCH_START';
export const MEDIUM_COLLECTIONS_FETCH_SUCCESS = 'COLLECTION/MEDIUM_COLLECTIONS_FETCH_SUCCESS';
export const MEDIUM_COLLECTIONS_FETCH_ERROR = 'COLLECTION/MEDIUM_COLLECTIONS_FETCH_ERROR';

export const COLLECTION_FETCH_START = 'COLLECTION/COLLECTION_FETCH_START';
export const COLLECTION_FETCH_SUCCESS = 'COLLECTION/COLLECTION_FETCH_SUCCESS';
export const COLLECTION_FETCH_ERROR = 'COLLECTION/COLLECTION_FETCH_ERROR';

export const COLLECTION_PERSIST_START = 'COLLECTION/COLLECTION_PERSIST_START';
export const COLLECTION_PERSIST_SUCCESS = 'COLLECTION/COLLECTION_PERSIST_SUCCESS';
export const COLLECTION_PERSIST_ERROR = 'COLLECTION/COLLECTION_PERSIST_ERROR';

export const COLLECTION_DELETE_START = 'COLLECTION/COLLECTION_DELETE_START';
export const COLLECTION_DELETE_SUCCESS = 'COLLECTION/COLLECTION_DELETE_SUCCESS';
export const COLLECTION_DELETE_ERROR = 'COLLECTION/COLLECTION_DELETE_ERROR';

export const fetchMediumCollections = makeApiActionCreator(api.fetchMediumCollections, MEDIUM_COLLECTIONS_FETCH_START, MEDIUM_COLLECTIONS_FETCH_SUCCESS, MEDIUM_COLLECTIONS_FETCH_ERROR);
export const fetchCollection = makeApiActionCreator(api.fetchCollection, COLLECTION_FETCH_START, COLLECTION_FETCH_SUCCESS, COLLECTION_FETCH_ERROR);
export const persistCollection = makeApiActionCreator(api.persistCollection, COLLECTION_PERSIST_START, COLLECTION_PERSIST_SUCCESS, COLLECTION_PERSIST_ERROR);
export const deleteCollection = makeApiActionCreator(api.deleteCollection, COLLECTION_DELETE_START, COLLECTION_DELETE_SUCCESS, COLLECTION_DELETE_ERROR);
