import * as api from '../api/collectionItem';
import { makeApiActionCreator } from './utils';

export const COLLECTION_ITEMS_FETCH_START = 'COLLECTION/COLLECTION_ITEMS_FETCH_START';
export const COLLECTION_ITEMS_FETCH_SUCCESS = 'COLLECTION/COLLECTION_ITEMS_FETCH_SUCCESS';
export const COLLECTION_ITEMS_FETCH_ERROR = 'COLLECTION/COLLECTION_ITEMS_FETCH_ERROR';

export const COLLECTION_ITEM_FETCH_START = 'COLLECTION/COLLECTION_ITEM_FETCH_START';
export const COLLECTION_ITEM_FETCH_SUCCESS = 'COLLECTION/COLLECTION_ITEM_FETCH_SUCCESS';
export const COLLECTION_ITEM_FETCH_ERROR = 'COLLECTION/COLLECTION_ITEM_FETCH_ERROR';

export const COLLECTION_ITEM_PERSIST_START = 'COLLECTION/COLLECTION_ITEM_PERSIST_START';
export const COLLECTION_ITEM_PERSIST_SUCCESS = 'COLLECTION/COLLECTION_ITEM_PERSIST_SUCCESS';
export const COLLECTION_ITEM_PERSIST_ERROR = 'COLLECTION/COLLECTION_ITEM_PERSIST_ERROR';

export const COLLECTION_ITEM_DELETE_START = 'COLLECTION/COLLECTION_ITEM_DELETE_START';
export const COLLECTION_ITEM_DELETE_SUCCESS = 'COLLECTION/COLLECTION_ITEM_DELETE_SUCCESS';
export const COLLECTION_ITEM_DELETE_ERROR = 'COLLECTION/COLLECTION_ITEM_DELETE_ERROR';

export const MOVE_COLLECTION_ITEM_START = 'COLLECTION/MOVE_COLLECTION_ITEM_START';
export const MOVE_COLLECTION_ITEM_SUCCESS = 'COLLECTION/MOVE_COLLECTION_ITEM_SUCCESS';
export const MOVE_COLLECTION_ITEM_ERROR = 'COLLECTION/MOVE_COLLECTION_ITEM_ERROR';

export const MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_START = 'COLLECTION/MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_START';
export const MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_SUCCESS = 'COLLECTION/MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_SUCCESS';
export const MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_ERROR = 'COLLECTION/MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_ERROR';

export const fetchCollectionItems = makeApiActionCreator(api.fetchCollectionItems, COLLECTION_ITEMS_FETCH_START, COLLECTION_ITEMS_FETCH_SUCCESS, COLLECTION_ITEMS_FETCH_ERROR);
export const fetchCollectionItem = makeApiActionCreator(api.fetchCollectionItem, COLLECTION_ITEM_FETCH_START, COLLECTION_ITEM_FETCH_SUCCESS, COLLECTION_ITEM_FETCH_ERROR);
export const persistCollectionItem = makeApiActionCreator(api.persistCollectionItem, COLLECTION_ITEM_PERSIST_START, COLLECTION_ITEM_PERSIST_SUCCESS, COLLECTION_ITEM_PERSIST_ERROR);
export const deleteCollectionItem = makeApiActionCreator(api.deleteCollectionItem, COLLECTION_ITEM_DELETE_START, COLLECTION_ITEM_DELETE_SUCCESS, COLLECTION_ITEM_DELETE_ERROR);
export const moveCollectionItem = makeApiActionCreator(api.moveCollectionItem, MOVE_COLLECTION_ITEM_START, MOVE_COLLECTION_ITEM_SUCCESS, MOVE_COLLECTION_ITEM_ERROR);
export const moveCollectionItemToOtherCollection = makeApiActionCreator(api.moveCollectionItemToOtherCollection, MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_START, MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_SUCCESS, MOVE_COLLECTION_ITEM_TO_OTHER_COLLECTION_ERROR);
