import * as api from '../api/collectionItem';
import { makeApiActionCreator } from './utils';

export const COLLECTION_ITEMS_FETCH_START = 'COLLECTION/COLLECTION_ITEMS_FETCH_START';
export const COLLECTION_ITEMS_FETCH_SUCCESS = 'COLLECTION/COLLECTION_ITEMS_FETCH_SUCCESS';
export const COLLECTION_ITEMS_FETCH_ERROR = 'COLLECTION/COLLECTION_ITEMS_FETCH_ERROR';

export const COLLECTION_ITEM_FETCH_START = 'COLLECTION/COLLECTION_ITEM_FETCH_START';
export const COLLECTION_ITEM_FETCH_SUCCESS = 'COLLECTION/COLLECTION_ITEM_FETCH_SUCCESS';
export const COLLECTION_ITEM_FETCH_ERROR = 'COLLECTION/COLLECTION_ITEM_FETCH_ERROR';

export const COLLECTION_ITEM_PERSIST_START = 'COLLECTION/COLLECTION_ITEM_PERSIST_START';
export const COLLECTION_ITEM_PERSIST_SUCCESS = 'COLLECTION/COLLECTION_ITEM_PERSIST_SUCCESS';
export const COLLECTION_ITEM_PERSIST_ERROR = 'COLLECTION/COLLECTION_ITEM_PERSIST_ERROR';

export const COLLECTION_ITEM_DELETE_START = 'COLLECTION/COLLECTION_ITEM_DELETE_START';
export const COLLECTION_ITEM_DELETE_SUCCESS = 'COLLECTION/COLLECTION_ITEM_DELETE_SUCCESS';
export const COLLECTION_ITEM_DELETE_ERROR = 'COLLECTION/COLLECTION_ITEM_DELETE_ERROR';

export const fetchCollectionItems = makeApiActionCreator(api.fetchCollectionItems, COLLECTION_ITEMS_FETCH_START, COLLECTION_ITEMS_FETCH_SUCCESS, COLLECTION_ITEMS_FETCH_ERROR);
export const fetchCollectionItem = makeApiActionCreator(api.fetchCollectionItem, COLLECTION_ITEM_FETCH_START, COLLECTION_ITEM_FETCH_SUCCESS, COLLECTION_ITEM_FETCH_ERROR);
export const persistCollectionItem = makeApiActionCreator(api.persistCollectionItem, COLLECTION_ITEM_PERSIST_START, COLLECTION_ITEM_PERSIST_SUCCESS, COLLECTION_ITEM_PERSIST_ERROR);
export const deleteCollectionItem = makeApiActionCreator(api.deleteCollectionItem, COLLECTION_ITEM_DELETE_START, COLLECTION_ITEM_DELETE_SUCCESS, COLLECTION_ITEM_DELETE_ERROR);
