import { makeApiActionCreator } from './utils';
import * as commercialApi from '../api/commercial';

export const COMMERCIALS_FETCH_START = 'COMMERCIALS/COMMERCIALS_FETCH_START';
export const COMMERCIALS_FETCH_SUCCESS = 'COMMERCIALS/COMMERCIALS_FETCH_SUCCESS';
export const COMMERCIALS_FETCH_ERROR = 'COMMERCIALS/COMMERCIALS_FETCH_ERROR';

export const COMMERCIAL_FETCH_START = 'COMMERCIALS/COMMERCIAL_FETCH_START';
export const COMMERCIAL_FETCH_SUCCESS = 'COMMERCIALS/COMMERCIAL_FETCH_SUCCESS';
export const COMMERCIAL_FETCH_ERROR = 'COMMERCIALS/COMMERCIAL_FETCH_ERROR';

export const COMMERCIAL_PERSIST_START = 'COMMERCIALS/COMMERCIAL_PERSIST_START';
export const COMMERCIAL_PERSIST_SUCCESS = 'COMMERCIALS/COMMERCIAL_PERSIST_SUCCESS';
export const COMMERCIAL_PERSIST_ERROR = 'COMMERCIALS/COMMERCIAL_PERSIST_ERROR';

export const COMMERCIAL_DELETE_START = 'COMMERCIALS/COMMERCIAL_DELETE_START';
export const COMMERCIAL_DELETE_SUCCESS = 'COMMERCIALS/COMMERCIAL_DELETE_SUCCESS';
export const COMMERCIAL_DELETE_ERROR = 'COMMERCIALS/COMMERCIAL_DELETE_ERROR';

export const COMMERCIALS_DELETE_START = 'COMMERCIALS/COMMERCIALS_DELETE_START';
export const COMMERCIALS_DELETE_SUCCESS = 'COMMERCIALS/COMMERCIALS_DELETE_SUCCESS';
export const COMMERCIALS_DELETE_ERROR = 'COMMERCIALS/COMMERCIALS_DELETE_ERROR';

export const UPLOAD_POSTER_IMAGE_START = 'COMMERCIALS/UPLOAD_POSTER_IMAGE_START';
export const UPLOAD_POSTER_IMAGE_SUCCESS = 'COMMERCIALS/UPLOAD_POSTER_IMAGE_SUCCESS';
export const UPLOAD_POSTER_IMAGE_ERROR = 'COMMERCIALS/UPLOAD_POSTER_IMAGE_ERROR';

export const UPLOAD_PROFILE_IMAGE_START = 'COMMERCIALS/UPLOAD_PROFILE_IMAGE_START';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'COMMERCIALS/UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_ERROR = 'COMMERCIALS/UPLOAD_PROFILE_IMAGE_ERROR';

export const UPLOAD_ROUND_LOGO_START = 'COMMERCIALS/UPLOAD_ROUND_LOGO_START';
export const UPLOAD_ROUND_LOGO_SUCCESS = 'COMMERCIALS/UPLOAD_ROUND_LOGO_SUCCESS';
export const UPLOAD_ROUND_LOGO_ERROR = 'COMMERCIALS/UPLOAD_ROUND_LOGO_ERROR';

export const fetchCommercials = makeApiActionCreator(commercialApi.fetchCommercials, COMMERCIALS_FETCH_START, COMMERCIALS_FETCH_SUCCESS, COMMERCIALS_FETCH_ERROR);
export const fetchCommercial = makeApiActionCreator(commercialApi.fetchCommercial, COMMERCIAL_FETCH_START, COMMERCIAL_FETCH_SUCCESS, COMMERCIAL_FETCH_ERROR);
export const persistCommercial = makeApiActionCreator(commercialApi.persistCommercial, COMMERCIAL_PERSIST_START, COMMERCIAL_PERSIST_SUCCESS, COMMERCIAL_PERSIST_ERROR);
export const deleteCommercials = makeApiActionCreator(commercialApi.deleteCommercials, COMMERCIALS_DELETE_START, COMMERCIALS_DELETE_SUCCESS, COMMERCIALS_DELETE_ERROR);
export const deleteCommercial = makeApiActionCreator(commercialApi.deleteCommercial, COMMERCIAL_DELETE_START, COMMERCIAL_DELETE_SUCCESS, COMMERCIAL_DELETE_ERROR);
export const uploadProfileImage = makeApiActionCreator(commercialApi.uploadProfileImage, UPLOAD_PROFILE_IMAGE_START, UPLOAD_PROFILE_IMAGE_SUCCESS, UPLOAD_PROFILE_IMAGE_ERROR);
export const uploadRoundLogo = makeApiActionCreator(commercialApi.uploadRoundLogo, UPLOAD_ROUND_LOGO_START, UPLOAD_ROUND_LOGO_SUCCESS, UPLOAD_ROUND_LOGO_ERROR);
