import * as api from '../api/contentProducers';
import { makeApiActionCreator } from './utils';

export const CONTENT_PRODUCERS_FETCH_START = 'CONTENT_PRODUCERS/CONTENT_PRODUCERS_FETCH_START';
export const CONTENT_PRODUCERS_FETCH_SUCCESS = 'CONTENT_PRODUCERS/CONTENT_PRODUCERS_FETCH_SUCCESS';
export const CONTENT_PRODUCERS_FETCH_ERROR = 'CONTENT_PRODUCERS/CONTENT_PRODUCERS_FETCH_ERROR';

export const fetchContentProducers = makeApiActionCreator(api.fetchContentProducers, CONTENT_PRODUCERS_FETCH_START, CONTENT_PRODUCERS_FETCH_SUCCESS, CONTENT_PRODUCERS_FETCH_ERROR);
