import * as api from '../api/datalabeltype';
//import * as api from '../api/broadcaster';
import { makeApiActionCreator } from './utils';

export const DATALABELTYPE_UPLOAD_IMAGE_START = 'DATALABELTYPE/DATALABELTYPE_UPLOAD_IMAGE_START';
export const DATALABELTYPE_UPLOAD_IMAGE_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_UPLOAD_IMAGE_SUCCESS';
export const DATALABELTYPE_UPLOAD_IMAGE_ERROR = 'DATALABELTYPE/DATALABELTYPE_UPLOAD_IMAGE_ERROR';

export const DATALABELTYPE_USERS_FETCH_START = 'DATALABELTYPE/DATALABELTYPE_USERS_FETCH_START';
export const DATALABELTYPE_USERS_FETCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_USERS_FETCH_SUCCESS';
export const DATALABELTYPE_USERS_FETCH_ERROR = 'DATALABELTYPE/DATALABELTYPE_USERS_FETCH_ERROR';

export const DATALABELTYPES_FETCH_START = 'DATALABELTYPE/DATALABELTYPES_FETCH_START';
export const DATALABELTYPES_FETCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPES_FETCH_SUCCESS';
export const DATALABELTYPES_FETCH_ERROR = 'DATALABELTYPE/DATALABELTYPES_FETCH_ERROR';

export const DATALABELTYPE_FETCH_START = 'DATALABELTYPE/DATALABELTYPE_FETCH_START';
export const DATALABELTYPE_FETCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_FETCH_SUCCESS';
export const DATALABELTYPE_FETCH_ERROR = 'DATALABELTYPE/DATALABELTYPE_FETCH_ERROR';

export const DATALABELTYPE_CHANNELS_FETCH_START = 'DATALABELTYPE/DATALABELTYPE_CHANNELS_FETCH_START';
export const DATALABELTYPE_CHANNELS_FETCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_CHANNELS_FETCH_SUCCESS';
export const DATALABELTYPE_CHANNELS_FETCH_ERROR = 'DATALABELTYPE/DATALABELTYPE_CHANNELS_FETCH_ERROR';

export const DATALABELTYPE_PERSIST_START = 'DATALABELTYPE/DATALABELTYPE_PERSIST_START';
export const DATALABELTYPE_PERSIST_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_PERSIST_SUCCESS';
export const DATALABELTYPE_PERSIST_ERROR = 'DATALABELTYPE/DATALABELTYPE_PERSIST_ERROR';

export const DATALABELTYPE_DELETE_START = 'DATALABELTYPE/DATALABELTYPE_DELETE_START';
export const DATALABELTYPE_DELETE_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_DELETE_SUCCESS';
export const DATALABELTYPE_DELETE_ERROR = 'DATALABELTYPE/DATALABELTYPE_DELETE_ERROR';

export const DATALABELTYPES_DELETE_START = 'DATALABELTYPE/DATALABELTYPES_DELETE_START';
export const DATALABELTYPES_DELETE_SUCCESS = 'DATALABELTYPE/DATALABELTYPES_DELETE_SUCCESS';
export const DATALABELTYPES_DELETE_ERROR = 'DATALABELTYPE/DATALABELTYPES_DELETE_ERROR';

export const DATALABELTYPE_SEARCH_START = 'DATALABELTYPE/DATALABELTYPE_SEARCH_START';
export const DATALABELTYPE_SEARCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_SEARCH_SUCCESS';
export const DATALABELTYPE_SEARCH_ERROR = 'DATALABELTYPE/DATALABELTYPE_SEARCH_ERROR';

export const DATALABELTYPE_CHANNELS_SEARCH_START = 'DATALABELTYPE/DATALABELTYPE_CHANNELS_SEARCH_START';
export const DATALABELTYPE_CHANNELS_SEARCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_CHANNELS_SEARCH_SUCCESS';
export const DATALABELTYPE_CHANNELS_SEARCH_ERROR = 'DATALABELTYPE/DATALABELTYPE_CHANNELS_SEARCH_ERROR';

export const DATALABELTYPE_MEDIA_SEARCH_START = 'DATALABELTYPE/DATALABELTYPE_MEDIA_SEARCH_START';
export const DATALABELTYPE_MEDIA_SEARCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_MEDIA_SEARCH_SUCCESS';
export const DATALABELTYPE_MEDIA_SEARCH_ERROR = 'DATALABELTYPE/DATALABELTYPE_MEDIA_SEARCH_ERROR';

export const DATALABELTYPE_LINK_USER_PERSIST_START = 'DATALABELTYPE/LINK_USER_PERSIST_START';
export const DATALABELTYPE_LINK_USER_PERSIST_SUCCESS = 'DATALABELTYPE/LINK_USER_PERSIST_SUCCESS';
export const DATALABELTYPE_LINK_USER_PERSIST_ERROR = 'DATALABELTYPE/LINK_USER_PERSIST_ERROR';

export const DATALABELTYPE_LINK_USER_DELETE_START = 'DATALABELTYPE/LINK_USER_DELETE_START';
export const DATALABELTYPE_LINK_USER_DELETE_SUCCESS = 'DATALABELTYPE/LINK_USER_DELETE_SUCCESS';
export const DATALABELTYPE_LINK_USER_DELETE_ERROR = 'DATALABELTYPE/LINK_USER_DELETE_ERROR';

export const DATALABELTYPE_LINK_USERS_DELETE_START = 'DATALABELTYPE/LINK_USERS_DELETE_START';
export const DATALABELTYPE_LINK_USERS_DELETE_SUCCESS = 'DATALABELTYPE/LINK_USERS_DELETE_SUCCESS';
export const DATALABELTYPE_LINK_USERS_DELETE_ERROR = 'DATALABELTYPE/LINK_USERS_DELETE_ERROR';

export const LOGO_DELETE_START = 'DATALABELTYPE/LOGO_DELETE_START';
export const LOGO_DELETE_SUCCESS = 'DATALABELTYPE/LOGO_DELETE_SUCCESS';
export const LOGO_DELETE_ERROR = 'DATALABELTYPE/LOGO_DELETE_ERROR';

export const fetchDatalabeltypeUsers = makeApiActionCreator(api.fetchDatalabeltypeUsers, DATALABELTYPE_USERS_FETCH_START, DATALABELTYPE_USERS_FETCH_SUCCESS, DATALABELTYPE_UPLOAD_IMAGE_ERROR);
export const fetchDatalabeltypes = makeApiActionCreator(api.fetchDatalabeltypes, DATALABELTYPES_FETCH_START, DATALABELTYPES_FETCH_SUCCESS, DATALABELTYPES_FETCH_ERROR);
export const fetchDatalabeltype = makeApiActionCreator(api.fetchDatalabeltype, DATALABELTYPE_FETCH_START, DATALABELTYPE_FETCH_SUCCESS, DATALABELTYPE_FETCH_ERROR);
//export const fetchBroadcasterChannels = makeApiActionCreator(api.fetchBroadcasterChannels, DATALABELTYPE_CHANNELS_FETCH_START, DATALABELTYPE_CHANNELS_FETCH_SUCCESS, DATALABELTYPE_CHANNELS_FETCH_ERROR);
export const persistLinkUser = makeApiActionCreator(api.persistLinkUser, DATALABELTYPE_LINK_USER_PERSIST_START, DATALABELTYPE_LINK_USER_PERSIST_SUCCESS, DATALABELTYPE_LINK_USER_PERSIST_ERROR);
export const persistDatalabeltype = makeApiActionCreator(api.persistDatalabeltype, DATALABELTYPE_PERSIST_START, DATALABELTYPE_PERSIST_SUCCESS, DATALABELTYPE_PERSIST_ERROR);
export const deleteLinkUser = makeApiActionCreator(api.deleteLinkUser, DATALABELTYPE_LINK_USER_DELETE_START, DATALABELTYPE_LINK_USER_DELETE_SUCCESS, DATALABELTYPE_LINK_USER_DELETE_ERROR);
export const deleteLinkUsers = makeApiActionCreator(api.deleteLinkUsers, DATALABELTYPE_LINK_USERS_DELETE_START, DATALABELTYPE_LINK_USERS_DELETE_SUCCESS, DATALABELTYPE_LINK_USERS_DELETE_ERROR);
export const deleteDatalabeltypes = makeApiActionCreator(api.deleteDatalabeltypes, DATALABELTYPES_DELETE_START, DATALABELTYPES_DELETE_SUCCESS, DATALABELTYPES_DELETE_ERROR);
export const deleteDatalabeltype = makeApiActionCreator(api.deleteDatalabeltype, DATALABELTYPE_DELETE_START, DATALABELTYPE_DELETE_SUCCESS, DATALABELTYPE_DELETE_ERROR);
export const deleteLogo = makeApiActionCreator(api.deleteLogo, LOGO_DELETE_START, LOGO_DELETE_SUCCESS, LOGO_DELETE_ERROR);
export const searchDatalabeltypes = makeApiActionCreator(api.searchDatalabeltypes, DATALABELTYPE_SEARCH_START, DATALABELTYPE_SEARCH_SUCCESS, DATALABELTYPE_SEARCH_ERROR);
export const uploadDatalabeltypeImage = makeApiActionCreator(api.uploadDatalabeltypeImage, DATALABELTYPE_UPLOAD_IMAGE_START, DATALABELTYPE_UPLOAD_IMAGE_SUCCESS, DATALABELTYPE_UPLOAD_IMAGE_ERROR);
export const searchDatalabeltypeChannels = makeApiActionCreator(api.searchDatalabeltypeChannels, DATALABELTYPE_CHANNELS_SEARCH_START, DATALABELTYPE_CHANNELS_SEARCH_SUCCESS, DATALABELTYPE_CHANNELS_SEARCH_ERROR);
export const searchDatalabeltypeMedia = makeApiActionCreator(api.searchDatalabeltypeMedia, DATALABELTYPE_MEDIA_SEARCH_START, DATALABELTYPE_MEDIA_SEARCH_SUCCESS, DATALABELTYPE_MEDIA_SEARCH_ERROR);


//export const fetchDatalabeltypeUsers = makeApiActionCreator(api.fetchBroadcasterUsers, DATALABELTYPE_USERS_FETCH_START, DATALABELTYPE_USERS_FETCH_SUCCESS, DATALABELTYPE_UPLOAD_IMAGE_ERROR);
//export const fetchDatalabeltypes = makeApiActionCreator(api.fetchBroadcasters, DATALABELTYPES_FETCH_START, DATALABELTYPES_FETCH_SUCCESS, DATALABELTYPES_FETCH_ERROR);
//export const fetchDatalabeltype = makeApiActionCreator(api.fetchBroadcaster, DATALABELTYPE_FETCH_START, DATALABELTYPE_FETCH_SUCCESS, DATALABELTYPE_FETCH_ERROR);
//export const fetchBroadcasterChannels = makeApiActionCreator(api.fetchBroadcasterChannels, DATALABELTYPE_CHANNELS_FETCH_START, DATALABELTYPE_CHANNELS_FETCH_SUCCESS, DATALABELTYPE_CHANNELS_FETCH_ERROR);
//export const persistLinkUser = makeApiActionCreator(api.persistLinkUser, DATALABELTYPE_LINK_USER_PERSIST_START, DATALABELTYPE_LINK_USER_PERSIST_SUCCESS, DATALABELTYPE_LINK_USER_PERSIST_ERROR);
//export const persistDatalabeltype = makeApiActionCreator(api.persistBroadcaster, DATALABELTYPE_PERSIST_START, DATALABELTYPE_PERSIST_SUCCESS, DATALABELTYPE_PERSIST_ERROR);
//export const deleteLinkUser = makeApiActionCreator(api.deleteLinkUser, DATALABELTYPE_LINK_USER_DELETE_START, DATALABELTYPE_LINK_USER_DELETE_SUCCESS, DATALABELTYPE_LINK_USER_DELETE_ERROR);
//export const deleteLinkUsers = makeApiActionCreator(api.deleteLinkUsers, DATALABELTYPE_LINK_USERS_DELETE_START, DATALABELTYPE_LINK_USERS_DELETE_SUCCESS, DATALABELTYPE_LINK_USERS_DELETE_ERROR);
//export const deleteDatalabeltypes = makeApiActionCreator(api.deleteBroadcasters, DATALABELTYPES_DELETE_START, DATALABELTYPES_DELETE_SUCCESS, DATALABELTYPES_DELETE_ERROR);
//export const deleteDatalabeltype = makeApiActionCreator(api.deleteBroadcaster, DATALABELTYPE_DELETE_START, DATALABELTYPE_DELETE_SUCCESS, DATALABELTYPE_DELETE_ERROR);
//export const deleteLogo = makeApiActionCreator(api.deleteLogo, LOGO_DELETE_START, LOGO_DELETE_SUCCESS, LOGO_DELETE_ERROR);
//export const searchDatalabeltypes = makeApiActionCreator(api.searchBroadcasters, DATALABELTYPE_SEARCH_START, DATALABELTYPE_SEARCH_SUCCESS, DATALABELTYPE_SEARCH_ERROR);
//export const uploadDatalabeltypeImage = makeApiActionCreator(api.uploadBroadcasterImage, DATALABELTYPE_UPLOAD_IMAGE_START, DATALABELTYPE_UPLOAD_IMAGE_SUCCESS, DATALABELTYPE_UPLOAD_IMAGE_ERROR);
//export const searchDatalabeltypeChannels = makeApiActionCreator(api.searchBroadcasterChannels, DATALABELTYPE_CHANNELS_SEARCH_START, DATALABELTYPE_CHANNELS_SEARCH_SUCCESS, DATALABELTYPE_CHANNELS_SEARCH_ERROR);
//export const searchDatalabeltypeMedia = makeApiActionCreator(api.searchBroadcasterMedia, DATALABELTYPE_MEDIA_SEARCH_START, DATALABELTYPE_MEDIA_SEARCH_SUCCESS, DATALABELTYPE_MEDIA_SEARCH_ERROR);
