import * as api from '../api/datalabel';
import { makeApiActionCreator } from './utils';

export const DATALABELS_FETCH_START = 'DATALABEL/DATALABELS_FETCH_START';
export const DATALABELS_FETCH_SUCCESS = 'DATALABEL/DATALABELS_FETCH_SUCCESS';
export const DATALABELS_FETCH_ERROR = 'DATALABEL/DATALABELS_FETCH_ERROR';

export const DATALABEL_FETCH_START = 'DATALABEL/DATALABEL_FETCH_START';
export const DATALABEL_FETCH_SUCCESS = 'DATALABEL/DATALABEL_FETCH_SUCCESS';
export const DATALABEL_FETCH_ERROR = 'DATALABEL/DATALABEL_FETCH_ERROR';

export const DATALABEL_PERSIST_START = 'DATALABEL/DATALABEL_PERSIST_START';
export const DATALABEL_PERSIST_SUCCESS = 'DATALABEL/DATALABEL_PERSIST_SUCCESS';
export const DATALABEL_PERSIST_ERROR = 'DATALABEL/DATALABEL_PERSIST_ERROR';

export const DATALABEL_DELETE_START = 'DATALABEL/DATALABEL_DELETE_START';
export const DATALABEL_DELETE_SUCCESS = 'DATALABEL/DATALABEL_DELETE_SUCCESS';
export const DATALABEL_DELETE_ERROR = 'DATALABEL/DATALABEL_DELETE_ERROR';

export const DATALABELS_DELETE_START = 'DATALABEL/DATALABELS_DELETE_START';
export const DATALABELS_DELETE_SUCCESS = 'DATALABEL/DATALABELS_DELETE_SUCCESS';
export const DATALABELS_DELETE_ERROR = 'DATALABEL/DATALABELS_DELETE_ERROR';

export const fetchDatalabels = makeApiActionCreator(api.fetchDatalabels, DATALABELS_FETCH_START, DATALABELS_FETCH_SUCCESS, DATALABELS_FETCH_ERROR);
export const fetchDatalabel = makeApiActionCreator(api.fetchDatalabel, DATALABEL_FETCH_START, DATALABEL_FETCH_SUCCESS, DATALABEL_FETCH_ERROR);
export const persistDatalabel = makeApiActionCreator(api.persistDatalabel, DATALABEL_PERSIST_START, DATALABEL_PERSIST_SUCCESS, DATALABEL_PERSIST_ERROR);
export const deleteDatalabels = makeApiActionCreator(api.deleteDatalabels, DATALABELS_DELETE_START, DATALABELS_DELETE_SUCCESS, DATALABELS_DELETE_ERROR);
export const deleteDatalabel = makeApiActionCreator(api.deleteDatalabel, DATALABEL_DELETE_START, DATALABEL_DELETE_SUCCESS, DATALABEL_DELETE_ERROR);
