import * as api from '../api/datalabeltype';
//import * as api from '../api/broadcaster';
import { makeApiActionCreator } from './utils';

export const DATALABELTYPES_FETCH_START = 'DATALABELTYPE/DATALABELTYPES_FETCH_START';
export const DATALABELTYPES_FETCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPES_FETCH_SUCCESS';
export const DATALABELTYPES_FETCH_ERROR = 'DATALABELTYPE/DATALABELTYPES_FETCH_ERROR';

export const DATALABELTYPE_FETCH_START = 'DATALABELTYPE/DATALABELTYPE_FETCH_START';
export const DATALABELTYPE_FETCH_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_FETCH_SUCCESS';
export const DATALABELTYPE_FETCH_ERROR = 'DATALABELTYPE/DATALABELTYPE_FETCH_ERROR';

export const DATALABELTYPE_PERSIST_START = 'DATALABELTYPE/DATALABELTYPE_PERSIST_START';
export const DATALABELTYPE_PERSIST_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_PERSIST_SUCCESS';
export const DATALABELTYPE_PERSIST_ERROR = 'DATALABELTYPE/DATALABELTYPE_PERSIST_ERROR';

export const DATALABELTYPE_DELETE_START = 'DATALABELTYPE/DATALABELTYPE_DELETE_START';
export const DATALABELTYPE_DELETE_SUCCESS = 'DATALABELTYPE/DATALABELTYPE_DELETE_SUCCESS';
export const DATALABELTYPE_DELETE_ERROR = 'DATALABELTYPE/DATALABELTYPE_DELETE_ERROR';

export const DATALABELTYPES_DELETE_START = 'DATALABELTYPE/DATALABELTYPES_DELETE_START';
export const DATALABELTYPES_DELETE_SUCCESS = 'DATALABELTYPE/DATALABELTYPES_DELETE_SUCCESS';
export const DATALABELTYPES_DELETE_ERROR = 'DATALABELTYPE/DATALABELTYPES_DELETE_ERROR';

export const fetchDatalabeltypes = makeApiActionCreator(api.fetchDatalabeltypes, DATALABELTYPES_FETCH_START, DATALABELTYPES_FETCH_SUCCESS, DATALABELTYPES_FETCH_ERROR);
export const fetchDatalabeltype = makeApiActionCreator(api.fetchDatalabeltype, DATALABELTYPE_FETCH_START, DATALABELTYPE_FETCH_SUCCESS, DATALABELTYPE_FETCH_ERROR);
export const persistDatalabeltype = makeApiActionCreator(api.persistDatalabeltype, DATALABELTYPE_PERSIST_START, DATALABELTYPE_PERSIST_SUCCESS, DATALABELTYPE_PERSIST_ERROR);
export const deleteDatalabeltypes = makeApiActionCreator(api.deleteDatalabeltypes, DATALABELTYPES_DELETE_START, DATALABELTYPES_DELETE_SUCCESS, DATALABELTYPES_DELETE_ERROR);
export const deleteDatalabeltype = makeApiActionCreator(api.deleteDatalabeltype, DATALABELTYPE_DELETE_START, DATALABELTYPE_DELETE_SUCCESS, DATALABELTYPE_DELETE_ERROR);
