import { makeApiActionCreator } from './utils';
import * as epsiodeApi from '../api/episode';

export const EPISODES_FETCH_START = 'EPISODES/EPISODES_FETCH_START';
export const EPISODES_FETCH_SUCCESS = 'EPISODES/EPISODES_FETCH_SUCCESS';
export const EPISODES_FETCH_ERROR = 'EPISODES/EPISODES_FETCH_ERROR';

export const EPISODE_FETCH_START = 'EPISODES/EPISODE_FETCH_START';
export const EPISODE_FETCH_SUCCESS = 'EPISODES/EPISODE_FETCH_SUCCESS';
export const EPISODE_FETCH_ERROR = 'EPISODES/EPISODE_FETCH_ERROR';

export const EPISODE_PERSIST_START = 'EPISODES/EPISODE_PERSIST_START';
export const EPISODE_PERSIST_SUCCESS = 'EPISODES/EPISODE_PERSIST_SUCCESS';
export const EPISODE_PERSIST_ERROR = 'EPISODES/EPISODE_PERSIST_ERROR';

export const EPISODE_DELETE_START = 'EPISODES/EPISODE_DELETE_START';
export const EPISODE_DELETE_SUCCESS = 'EPISODES/EPISODE_DELETE_SUCCESS';
export const EPISODE_DELETE_ERROR = 'EPISODES/EPISODE_DELETE_ERROR';

export const EPISODES_DELETE_START = 'EPISODES/EPISODES_DELETE_START';
export const EPISODES_DELETE_SUCCESS = 'EPISODES/EPISODES_DELETE_SUCCESS';
export const EPISODES_DELETE_ERROR = 'EPISODES/EPISODES_DELETE_ERROR';

export const fetchEpisodes = makeApiActionCreator(epsiodeApi.fetchEpisodes, EPISODES_FETCH_START, EPISODES_FETCH_SUCCESS, EPISODES_FETCH_ERROR);
export const fetchEpisode = makeApiActionCreator(epsiodeApi.fetchEpisode, EPISODE_FETCH_START, EPISODE_FETCH_SUCCESS, EPISODE_FETCH_ERROR);
export const persistEpisode = makeApiActionCreator(epsiodeApi.persistEpisode, EPISODE_PERSIST_START, EPISODE_PERSIST_SUCCESS, EPISODE_PERSIST_ERROR);
export const deleteEpisodes = makeApiActionCreator(epsiodeApi.deleteEpisodes, EPISODES_DELETE_START, EPISODES_DELETE_SUCCESS, EPISODES_DELETE_ERROR);
export const deleteEpisode = makeApiActionCreator(epsiodeApi.deleteEpisode, EPISODE_DELETE_START, EPISODE_DELETE_SUCCESS, EPISODE_DELETE_ERROR);
