import * as api from '../api/mediumCategory';
import { makeApiActionCreator } from './utils';

export const MEDIUM_CATEGORIES_SEARCH_START = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_SEARCH_START';
export const MEDIUM_CATEGORIES_SEARCH_SUCCESS = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_SEARCH_SUCCESS';
export const MEDIUM_CATEGORIES_SEARCH_ERROR = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_SEARCH_ERROR';

export const MEDIUM_CATEGORIES_FETCH_START = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_FETCH_START';
export const MEDIUM_CATEGORIES_FETCH_SUCCESS = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_FETCH_SUCCESS';
export const MEDIUM_CATEGORIES_FETCH_ERROR = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_FETCH_ERROR';

export const fetchMediumCategories = makeApiActionCreator(api.fetchMediumCategories, MEDIUM_CATEGORIES_FETCH_START, MEDIUM_CATEGORIES_FETCH_SUCCESS, MEDIUM_CATEGORIES_FETCH_ERROR);
export const searchMediumCategories = makeApiActionCreator(api.searchMediumCategories, MEDIUM_CATEGORIES_SEARCH_START, MEDIUM_CATEGORIES_SEARCH_SUCCESS, MEDIUM_CATEGORIES_SEARCH_ERROR);
