import * as api from '../api/mediumCategory';
import { makeApiActionCreator } from './utils';

export const MEDIUM_CATEGORIES_SEARCH_START = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_SEARCH_START';
export const MEDIUM_CATEGORIES_SEARCH_SUCCESS = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_SEARCH_SUCCESS';
export const MEDIUM_CATEGORIES_SEARCH_ERROR = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_SEARCH_ERROR';

export const MEDIUM_CATEGORIES_FETCH_START = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_FETCH_START';
export const MEDIUM_CATEGORIES_FETCH_SUCCESS = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_FETCH_SUCCESS';
export const MEDIUM_CATEGORIES_FETCH_ERROR = 'MEDIUM_CATEGORY/MEDIUM_CATEGORIES_FETCH_ERROR';

export const MEDIUM_CATEGORY_FETCH_START = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_FETCH_START';
export const MEDIUM_CATEGORY_FETCH_SUCCESS = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_FETCH_SUCCESS';
export const MEDIUM_CATEGORY_FETCH_ERROR = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_FETCH_ERROR';

export const MEDIUM_CATEGORY_PERSIST_START = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_PERSIST_START';
export const MEDIUM_CATEGORY_PERSIST_SUCCESS = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_PERSIST_SUCCESS';
export const MEDIUM_CATEGORY_PERSIST_ERROR = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_PERSIST_ERROR';

export const MEDIUM_CATEGORY_DELETE_START = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_DELETE_START';
export const MEDIUM_CATEGORY_DELETE_SUCCESS = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_DELETE_SUCCESS';
export const MEDIUM_CATEGORY_DELETE_ERROR = 'MEDIUM_CATEGORY/MEDIUM_CATEGORY_DELETE_ERROR';

export const fetchMediumCategories = makeApiActionCreator(api.fetchMediumCategories, MEDIUM_CATEGORIES_FETCH_START, MEDIUM_CATEGORIES_FETCH_SUCCESS, MEDIUM_CATEGORIES_FETCH_ERROR);
export const fetchMediumCategory = makeApiActionCreator(api.fetchMediumCategory, MEDIUM_CATEGORY_FETCH_START, MEDIUM_CATEGORY_FETCH_SUCCESS, MEDIUM_CATEGORY_FETCH_ERROR);
export const searchMediumCategories = makeApiActionCreator(api.searchMediumCategories, MEDIUM_CATEGORIES_SEARCH_START, MEDIUM_CATEGORIES_SEARCH_SUCCESS, MEDIUM_CATEGORIES_SEARCH_ERROR);
export const persistMediumCategory = makeApiActionCreator(api.persistMediumCategory, MEDIUM_CATEGORY_PERSIST_START, MEDIUM_CATEGORY_PERSIST_SUCCESS, MEDIUM_CATEGORY_PERSIST_ERROR);
export const deleteMediumCategory = makeApiActionCreator(api.deleteMediumCategory, MEDIUM_CATEGORY_DELETE_START, MEDIUM_CATEGORY_DELETE_SUCCESS, MEDIUM_CATEGORY_DELETE_ERROR);
