import * as api from '../api/movie';
import { makeApiActionCreator } from './utils';

export const MOVIES_SEARCH_START = 'MOVIE/MOVIES_SEARCH_START';
export const MOVIES_SEARCH_SUCCESS = 'MOVIE/MOVIES_SEARCH_SUCCESS';
export const MOVIES_SEARCH_ERROR = 'MOVIE/MOVIES_SEARCH_ERROR';

export const MOVIES_FETCH_START = 'MOVIE/MOVIES_FETCH_START';
export const MOVIES_FETCH_SUCCESS = 'MOVIE/MOVIES_FETCH_SUCCESS';
export const MOVIES_FETCH_ERROR = 'MOVIE/MOVIES_FETCH_ERROR';

export const MOVIE_FETCH_START = 'MOVIE/MOVIE_FETCH_START';
export const MOVIE_FETCH_SUCCESS = 'MOVIE/MOVIE_FETCH_SUCCESS';
export const MOVIE_FETCH_ERROR = 'MOVIE/MOVIE_FETCH_ERROR';

export const MOVIE_PERSIST_START = 'MOVIE/MOVIE_PERSIST_START';
export const MOVIE_PERSIST_SUCCESS = 'MOVIE/MOVIE_PERSIST_SUCCESS';
export const MOVIE_PERSIST_ERROR = 'MOVIE/MOVIE_PERSIST_ERROR';

export const MOVIE_DELETE_START = 'MOVIE/MOVIE_DELETE_START';
export const MOVIE_DELETE_SUCCESS = 'MOVIE/MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_ERROR = 'MOVIE/MOVIE_DELETE_ERROR';

export const MOVIES_DELETE_START = 'MOVIE/MOVIES_DELETE_START';
export const MOVIES_DELETE_SUCCESS = 'MOVIE/MOVIES_DELETE_SUCCESS';
export const MOVIES_DELETE_ERROR = 'MOVIE/MOVIES_DELETE_ERROR';

export const UPLOAD_POSTER_IMAGE_START = 'MOVIE/UPLOAD_POSTER_IMAGE_START';
export const UPLOAD_POSTER_IMAGE_SUCCESS = 'MOVIE/UPLOAD_POSTER_IMAGE_SUCCESS';
export const UPLOAD_POSTER_IMAGE_ERROR = 'MOVIE/UPLOAD_POSTER_IMAGE_ERROR';

export const UPLOAD_PROFILE_IMAGE_START = 'MOVIE/UPLOAD_PROFILE_IMAGE_START';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'MOVIE/UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_ERROR = 'MOVIE/UPLOAD_PROFILE_IMAGE_ERROR';

export const fetchMovies = makeApiActionCreator(api.fetchMovies, MOVIES_FETCH_START, MOVIES_FETCH_SUCCESS, MOVIES_FETCH_ERROR);
export const fetchMovie = makeApiActionCreator(api.fetchMovie, MOVIE_FETCH_START, MOVIE_FETCH_SUCCESS, MOVIE_FETCH_ERROR);
export const persistMovie = makeApiActionCreator(api.persistMovie, MOVIE_PERSIST_START, MOVIE_PERSIST_SUCCESS, MOVIE_PERSIST_ERROR);
export const deleteMovies = makeApiActionCreator(api.deleteMovies, MOVIES_DELETE_START, MOVIES_DELETE_SUCCESS, MOVIES_DELETE_ERROR);
export const deleteMovie = makeApiActionCreator(api.deleteMovie, MOVIE_DELETE_START, MOVIE_DELETE_SUCCESS, MOVIE_DELETE_ERROR);
export const searchMovies = makeApiActionCreator(api.searchMovies, MOVIES_SEARCH_START, MOVIES_SEARCH_SUCCESS, MOVIES_SEARCH_ERROR);
export const uploadPosterImage = makeApiActionCreator(api.uploadPosterImage, UPLOAD_POSTER_IMAGE_START, UPLOAD_POSTER_IMAGE_SUCCESS, UPLOAD_POSTER_IMAGE_ERROR);
export const uploadProfileImage = makeApiActionCreator(api.uploadProfileImage, UPLOAD_PROFILE_IMAGE_START, UPLOAD_PROFILE_IMAGE_SUCCESS, UPLOAD_PROFILE_IMAGE_ERROR);
