import * as api from '../api/person';
import { makeApiActionCreator } from './utils';

export const PERSON_SEARCH_START = 'PERSON/PERSON_SEARCH_START';
export const PERSON_SEARCH_SUCCESS = 'PERSON/PERSON_SEARCH_SUCCESS';
export const PERSON_SEARCH_ERROR = 'PERSON/PERSON_SEARCH_ERROR';

export const PERSONS_FETCH_START = 'PERSON/PERSONS_FETCH_START';
export const PERSONS_FETCH_SUCCESS = 'PERSON/PERSONS_FETCH_SUCCESS';
export const PERSONS_FETCH_ERROR = 'PERSON/PERSONS_FETCH_ERROR';

export const PERSON_DELETE_START = 'PERSON/PERSON_DELETE_START';
export const PERSON_DELETE_SUCCESS = 'PERSON/PERSON_DELETE_SUCCESS';
export const PERSON_DELETE_ERROR = 'PERSON/PERSON_DELETE_ERROR';

export const PERSONS_DELETE_START = 'PERSON/PERSONS_DELETE_START';
export const PERSONS_DELETE_SUCCESS = 'PERSON/PERSONS_DELETE_SUCCESS';
export const PERSONS_DELETE_ERROR = 'PERSON/PERSONS_DELETE_ERROR';

export const PERSON_PERSIST_START = 'PERSON/PERSON_PERSIST_START';
export const PERSON_PERSIST_SUCCESS = 'PERSON/PERSON_PERSIST_SUCCESS';
export const PERSON_PERSIST_ERROR = 'PERSON/PERSON_PERSIST_ERROR';

export const deletePersons = makeApiActionCreator(api.deletePersons, PERSONS_DELETE_START, PERSONS_DELETE_SUCCESS, PERSONS_DELETE_ERROR);
export const deletePerson = makeApiActionCreator(api.deletePerson, PERSON_DELETE_START, PERSON_DELETE_SUCCESS, PERSON_DELETE_ERROR);
export const fetchPersons = makeApiActionCreator(api.fetchPersons, PERSONS_FETCH_START, PERSONS_FETCH_SUCCESS, PERSONS_FETCH_ERROR);
export const persistPerson = makeApiActionCreator(api.persistPerson, PERSON_PERSIST_START, PERSON_PERSIST_SUCCESS, PERSON_PERSIST_ERROR);
export const searchPersons = makeApiActionCreator(api.searchPersons, PERSON_SEARCH_START, PERSON_SEARCH_SUCCESS, PERSON_SEARCH_ERROR);
