import * as api from '../api/person';
import { makeApiActionCreator } from './utils';

export const PERSON_SEARCH_START = 'PERSON/PERSON_SEARCH_START';
export const PERSON_SEARCH_SUCCESS = 'PERSON/PERSON_SEARCH_SUCCESS';
export const PERSON_SEARCH_ERROR = 'PERSON/PERSON_SEARCH_ERROR';

export const PERSONS_FETCH_START = 'PERSON/PERSONS_FETCH_START';
export const PERSONS_FETCH_SUCCESS = 'PERSON/PERSONS_FETCH_SUCCESS';
export const PERSONS_FETCH_ERROR = 'PERSON/PERSONS_FETCH_ERROR';

export const PERSON_FETCH_START = 'PERSON/PERSON_FETCH_START';
export const PERSON_FETCH_SUCCESS = 'PERSON/PERSON_FETCH_SUCCESS';
export const PERSON_FETCH_ERROR = 'PERSON/PERSON_FETCH_ERROR';

export const CHARACTER_FACE_IMAGES_FETCH_START = 'PERSON/CHARACTER_FACE_IMAGES_FETCH_START';
export const CHARACTER_FACE_IMAGES_FETCH_SUCCESS = 'PERSON/CHARACTER_FACE_IMAGES_FETCH_SUCCESS';
export const CHARACTER_FACE_IMAGES_FETCH_ERROR = 'PERSON/CHARACTER_FACE_IMAGES_FETCH_ERROR';

export const PERSON_DELETE_START = 'PERSON/PERSON_DELETE_START';
export const PERSON_DELETE_SUCCESS = 'PERSON/PERSON_DELETE_SUCCESS';
export const PERSON_DELETE_ERROR = 'PERSON/PERSON_DELETE_ERROR';

export const PERSONS_DELETE_START = 'PERSON/PERSONS_DELETE_START';
export const PERSONS_DELETE_SUCCESS = 'PERSON/PERSONS_DELETE_SUCCESS';
export const PERSONS_DELETE_ERROR = 'PERSON/PERSONS_DELETE_ERROR';

export const PERSON_PERSIST_START = 'PERSON/PERSON_PERSIST_START';
export const PERSON_PERSIST_SUCCESS = 'PERSON/PERSON_PERSIST_SUCCESS';
export const PERSON_PERSIST_ERROR = 'PERSON/PERSON_PERSIST_ERROR';

export const UPLOAD_PORTRAIT_IMAGE_START = 'PERSON/UPLOAD_PORTRAIT_IMAGE_START';
export const UPLOAD_PORTRAIT_IMAGE_SUCCESS = 'PERSON/UPLOAD_PORTRAIT_IMAGE_SUCCESS';
export const UPLOAD_PORTRAIT_IMAGE_ERROR = 'PERSON/UPLOAD_PORTRAIT_IMAGE_ERROR';

export const UPLOAD_PROFILE_IMAGE_START = 'PERSON/UPLOAD_PROFILE_IMAGE_START';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'PERSON/UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_ERROR = 'PERSON/UPLOAD_PROFILE_IMAGE_ERROR';

export const UPLOAD_FACE_IMAGE_START = 'PERSON/UPLOAD_FACE_IMAGE_START';
export const UPLOAD_FACE_IMAGE_SUCCESS = 'PERSON/UPLOAD_FACE_IMAGE_SUCCESS';
export const UPLOAD_FACE_IMAGE_ERROR = 'PERSON/UPLOAD_FACE_IMAGE_ERROR';

export const DELETE_PROFILE_IMAGE_START = 'PERSON/DELETE_PROFILE_IMAGE_START';
export const DELETE_PROFILE_IMAGE_SUCCESS = 'PERSON/DELETE_PROFILE_IMAGE_SUCCESS';
export const DELETE_PROFILE_IMAGE_ERROR = 'PERSON/DELETE_PROFILE_IMAGE_ERROR';

export const DELETE_POSTER_IMAGE_START = 'PERSON/DELETE_POSTER_IMAGE_START';
export const DELETE_POSTER_IMAGE_SUCCESS = 'PERSON/DELETE_POSTER_IMAGE_SUCCESS';
export const DELETE_POSTER_IMAGE_ERROR = 'PERSON/DELETE_POSTER_IMAGE_ERROR';

export const deletePortraitImage = makeApiActionCreator(api.deletePortraitImage, DELETE_POSTER_IMAGE_START, DELETE_POSTER_IMAGE_SUCCESS, DELETE_POSTER_IMAGE_ERROR);
export const deleteProfileImage = makeApiActionCreator(api.deleteProfileImage, DELETE_PROFILE_IMAGE_START, DELETE_PROFILE_IMAGE_SUCCESS, DELETE_PROFILE_IMAGE_ERROR);
export const deletePersons = makeApiActionCreator(api.deletePersons, PERSONS_DELETE_START, PERSONS_DELETE_SUCCESS, PERSONS_DELETE_ERROR);
export const deletePerson = makeApiActionCreator(api.deletePerson, PERSON_DELETE_START, PERSON_DELETE_SUCCESS, PERSON_DELETE_ERROR);
export const fetchPersons = makeApiActionCreator(api.fetchPersons, PERSONS_FETCH_START, PERSONS_FETCH_SUCCESS, PERSONS_FETCH_ERROR);
export const fetchPerson = makeApiActionCreator(api.fetchPerson, PERSON_FETCH_START, PERSON_FETCH_SUCCESS, PERSON_FETCH_ERROR);
export const fetchFaceImages = makeApiActionCreator(api.fetchFaceImages, CHARACTER_FACE_IMAGES_FETCH_START, CHARACTER_FACE_IMAGES_FETCH_SUCCESS, CHARACTER_FACE_IMAGES_FETCH_ERROR);
export const persistPerson = makeApiActionCreator(api.persistPerson, PERSON_PERSIST_START, PERSON_PERSIST_SUCCESS, PERSON_PERSIST_ERROR);
export const searchPersons = makeApiActionCreator(api.searchPersons, PERSON_SEARCH_START, PERSON_SEARCH_SUCCESS, PERSON_SEARCH_ERROR);
export const uploadPortraitImage = makeApiActionCreator(api.uploadPortraitImage, UPLOAD_PORTRAIT_IMAGE_START, UPLOAD_PORTRAIT_IMAGE_SUCCESS, UPLOAD_PORTRAIT_IMAGE_ERROR);
export const uploadProfileImage = makeApiActionCreator(api.uploadProfileImage, UPLOAD_PROFILE_IMAGE_START, UPLOAD_PROFILE_IMAGE_SUCCESS, UPLOAD_PROFILE_IMAGE_ERROR);
export const uploadFaceImage = makeApiActionCreator(api.uploadFaceImage, UPLOAD_FACE_IMAGE_START, UPLOAD_FACE_IMAGE_SUCCESS, UPLOAD_FACE_IMAGE_ERROR);
