import { makeApiActionCreator } from './utils';
import * as productOfferingApi from '../api/productOffering';

export const PRODUCT_OFFERING_DELETE_START = 'PRODUCT_OFFERING/PRODUCT_OFFERING_DELETE_START';
export const PRODUCT_OFFERING_DELETE_SUCCESS = 'PRODUCT_OFFERING/PRODUCT_OFFERING_DELETE_SUCCESS';
export const PRODUCT_OFFERING_DELETE_ERROR = 'PRODUCT_OFFERING/PRODUCT_OFFERING_DELETE_ERROR';

export const PRODUCT_OFFERINGS_FETCH_START = 'PRODUCT_OFFERING/PRODUCT_OFFERINGS_FETCH_START';
export const PRODUCT_OFFERINGS_FETCH_SUCCESS = 'PRODUCT_OFFERING/PRODUCT_OFFERINGS_FETCH_SUCCESS';
export const PRODUCT_OFFERINGS_FETCH_ERROR = 'PRODUCT_OFFERING/PRODUCT_OFFERINGS_FETCH_ERROR';

export const PRODUCT_OFFERING_PERSIST_START = 'PRODUCT_OFFERING/PRODUCT_OFFERING_PERSIST_START';
export const PRODUCT_OFFERING_PERSIST_SUCCESS = 'PRODUCT_OFFERING/PRODUCT_OFFERING_PERSIST_SUCCESS';
export const PRODUCT_OFFERING_PERSIST_ERROR = 'PRODUCT_OFFERING/PRODUCT_OFFERING_PERSIST_ERROR';

export const deleteProductOffering = makeApiActionCreator(productOfferingApi.deleteProductOffering, PRODUCT_OFFERING_DELETE_START, PRODUCT_OFFERING_DELETE_SUCCESS, PRODUCT_OFFERING_DELETE_ERROR);
export const fetchProductOfferings = makeApiActionCreator(productOfferingApi.fetchProductOfferings, PRODUCT_OFFERINGS_FETCH_START, PRODUCT_OFFERINGS_FETCH_SUCCESS, PRODUCT_OFFERINGS_FETCH_ERROR);
export const persistProductOffering = makeApiActionCreator(productOfferingApi.persistProductOffering, PRODUCT_OFFERING_PERSIST_START, PRODUCT_OFFERING_PERSIST_SUCCESS, PRODUCT_OFFERING_PERSIST_ERROR);
