import * as api from '../api/productCategory';
import { makeApiActionCreator } from './utils';

export const PRODUCT_CATEGORIES_SEARCH_START = 'PRODUCT_CATEGORY/PRODUCT_CATEGORIES_SEARCH_START';
export const PRODUCT_CATEGORIES_SEARCH_SUCCESS = 'PRODUCT_CATEGORY/PRODUCT_CATEGORIES_SEARCH_SUCCESS';
export const PRODUCT_CATEGORIES_SEARCH_ERROR = 'PRODUCT_CATEGORY/PRODUCT_CATEGORIES_SEARCH_ERROR';

export const PRODUCT_CATEGORIES_FETCH_START = 'PRODUCT_CATEGORY/PRODUCT_CATEGORIES_FETCH_START';
export const PRODUCT_CATEGORIES_FETCH_SUCCESS = 'PRODUCT_CATEGORY/PRODUCT_CATEGORIES_FETCH_SUCCESS';
export const PRODUCT_CATEGORIES_FETCH_ERROR = 'PRODUCT_CATEGORY/PRODUCT_CATEGORIES_FETCH_ERROR';

export const PRODUCT_CATEGORY_FETCH_START = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_FETCH_START';
export const PRODUCT_CATEGORY_FETCH_SUCCESS = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_FETCH_SUCCESS';
export const PRODUCT_CATEGORY_FETCH_ERROR = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_FETCH_ERROR';

export const PRODUCT_CATEGORY_PERSIST_START = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_PERSIST_START';
export const PRODUCT_CATEGORY_PERSIST_SUCCESS = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_PERSIST_SUCCESS';
export const PRODUCT_CATEGORY_PERSIST_ERROR = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_PERSIST_ERROR';

export const PRODUCT_CATEGORY_DELETE_START = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_DELETE_START';
export const PRODUCT_CATEGORY_DELETE_SUCCESS = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_DELETE_SUCCESS';
export const PRODUCT_CATEGORY_DELETE_ERROR = 'PRODUCT_CATEGORY/PRODUCT_CATEGORY_DELETE_ERROR';

export const fetchProductCategories = makeApiActionCreator(api.fetchProductCategories, PRODUCT_CATEGORIES_FETCH_START, PRODUCT_CATEGORIES_FETCH_SUCCESS, PRODUCT_CATEGORIES_FETCH_ERROR);
export const fetchProductCategory = makeApiActionCreator(api.fetchProductCategory, PRODUCT_CATEGORY_FETCH_START, PRODUCT_CATEGORY_FETCH_SUCCESS, PRODUCT_CATEGORY_FETCH_ERROR);
export const searchProductCategories = makeApiActionCreator(api.searchProductCategories, PRODUCT_CATEGORIES_SEARCH_START, PRODUCT_CATEGORIES_SEARCH_SUCCESS, PRODUCT_CATEGORIES_SEARCH_ERROR);
export const persistProductCategory = makeApiActionCreator(api.persistProductCategory, PRODUCT_CATEGORY_PERSIST_START, PRODUCT_CATEGORY_PERSIST_SUCCESS, PRODUCT_CATEGORY_PERSIST_ERROR);
export const deleteProductCategory = makeApiActionCreator(api.deleteProductCategory, PRODUCT_CATEGORY_DELETE_START, PRODUCT_CATEGORY_DELETE_SUCCESS, PRODUCT_CATEGORY_DELETE_ERROR);
