import * as api from '../api/product';
import { makeApiActionCreator } from './utils';

export const PRODUCT_SEARCH_START = 'PRODUCT/PRODUCT_SEARCH_START';
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT/PRODUCT_SEARCH_SUCCESS';
export const PRODUCT_SEARCH_ERROR = 'PRODUCT/PRODUCT_SEARCH_ERROR';

export const PRODUCTS_FETCH_START = 'PRODUCT/PRODUCTS_FETCH_START';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCT/PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_ERROR = 'PRODUCT/PRODUCTS_FETCH_ERROR';

export const UNASSIGNED_PRODUCTS_FETCH_START = 'PRODUCT/UNASSIGNED_PRODUCTS_FETCH_START';
export const UNASSIGNED_PRODUCTS_FETCH_SUCCESS = 'PRODUCT/UNASSIGNED_PRODUCTS_FETCH_SUCCESS';
export const UNASSIGNED_PRODUCTS_FETCH_ERROR = 'PRODUCT/UNASSIGNED_PRODUCTS_FETCH_ERROR';

export const SIMILAR_PRODUCTS_FETCH_START = 'PRODUCT/SIMILAR_PRODUCTS_FETCH_START';
export const SIMILAR_PRODUCTS_FETCH_SUCCESS = 'PRODUCT/SIMILAR_PRODUCTS_FETCH_SUCCESS';
export const SIMILAR_PRODUCTS_FETCH_ERROR = 'PRODUCT/SIMILAR_PRODUCTS_FETCH_ERROR';

export const PRODUCT_OFFERINGS_FETCH_START = 'PRODUCT/PRODUCT_OFFERINGS_FETCH_START';
export const PRODUCT_OFFERINGS_FETCH_SUCCESS = 'PRODUCT/PRODUCT_OFFERINGS_FETCH_SUCCESS';
export const PRODUCT_OFFERINGS_FETCH_ERROR = 'PRODUCT/PRODUCT_OFFERINGS_FETCH_ERROR';

export const SUGGESTED_PRODUCTS_FETCH_START = 'PRODUCT/SUGGESTED_PRODUCTS_FETCH_START';
export const SUGGESTED_PRODUCTS_FETCH_SUCCESS = 'PRODUCT/SUGGESTED_PRODUCTS_FETCH_SUCCESS';
export const SUGGESTED_PRODUCTS_FETCH_ERROR = 'PRODUCT/SUGGESTED_PRODUCTS_FETCH_ERROR';

export const PRODUCT_FETCH_START = 'PRODUCT/PRODUCT_FETCH_START';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT/PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_ERROR = 'PRODUCT/PRODUCT_FETCH_ERROR';

export const PRODUCT_DELETE_START = 'PRODUCT/PRODUCT_DELETE_START';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT/PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_ERROR = 'PRODUCT/PRODUCT_DELETE_ERROR';

export const PRODUCTS_DELETE_START = 'PRODUCT/PRODUCTS_DELETE_START';
export const PRODUCTS_DELETE_SUCCESS = 'PRODUCT/PRODUCTS_DELETE_SUCCESS';
export const PRODUCTS_DELETE_ERROR = 'PRODUCT/PRODUCTS_DELETE_ERROR';

export const PRODUCT_PERSIST_START = 'PRODUCT/PRODUCT_PERSIST_START';
export const PRODUCT_PERSIST_SUCCESS = 'PRODUCT/PRODUCT_PERSIST_SUCCESS';
export const PRODUCT_PERSIST_ERROR = 'PRODUCT/PRODUCT_PERSIST_ERROR';

export const UPLOAD_IMAGE_START = 'PRODUCT/UPLOAD_IMAGE_START';
export const UPLOAD_IMAGE_SUCCESS = 'PRODUCT/UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'PRODUCT/UPLOAD_IMAGE_ERROR';

export const DELETE_IMAGE_START = 'PRODUCT/DELETE_IMAGE_START';
export const DELETE_IMAGE_SUCCESS = 'PRODUCT/DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_ERROR = 'PRODUCT/DELETE_IMAGE_ERROR';

export const deleteProducts = makeApiActionCreator(api.deleteProducts, PRODUCTS_DELETE_START, PRODUCTS_DELETE_SUCCESS, PRODUCTS_DELETE_ERROR);
export const deleteProduct = makeApiActionCreator(api.deleteProduct, PRODUCT_DELETE_START, PRODUCT_DELETE_SUCCESS, PRODUCT_DELETE_ERROR);
export const fetchProducts = makeApiActionCreator(api.fetchProducts, PRODUCTS_FETCH_START, PRODUCTS_FETCH_SUCCESS, PRODUCTS_FETCH_ERROR);
export const fetchUnassignedProducts = makeApiActionCreator(api.fetchUnassignedProducts, UNASSIGNED_PRODUCTS_FETCH_START, UNASSIGNED_PRODUCTS_FETCH_SUCCESS, UNASSIGNED_PRODUCTS_FETCH_ERROR);
export const fetchProductOfferings = makeApiActionCreator(api.fetchProductOfferings, PRODUCT_OFFERINGS_FETCH_START, PRODUCT_OFFERINGS_FETCH_SUCCESS, PRODUCT_OFFERINGS_FETCH_ERROR);
export const fetchSimilarProducts = makeApiActionCreator(api.fetchSimilarProducts, SIMILAR_PRODUCTS_FETCH_START, SIMILAR_PRODUCTS_FETCH_SUCCESS, SIMILAR_PRODUCTS_FETCH_ERROR);
export const fetchSuggestedProducts = makeApiActionCreator(api.fetchSuggestedProducts, SUGGESTED_PRODUCTS_FETCH_START, SUGGESTED_PRODUCTS_FETCH_SUCCESS, SUGGESTED_PRODUCTS_FETCH_ERROR);
export const fetchProduct = makeApiActionCreator(api.fetchProduct, PRODUCT_FETCH_START, PRODUCT_FETCH_SUCCESS, PRODUCT_FETCH_ERROR);
export const persistProduct = makeApiActionCreator(api.persistProduct, PRODUCT_PERSIST_START, PRODUCT_PERSIST_SUCCESS, PRODUCT_PERSIST_ERROR);
export const searchProducts = makeApiActionCreator(api.searchProducts, PRODUCT_SEARCH_START, PRODUCT_SEARCH_SUCCESS, PRODUCT_SEARCH_ERROR);
export const uploadImage = makeApiActionCreator(api.uploadImage, UPLOAD_IMAGE_START, UPLOAD_IMAGE_SUCCESS, UPLOAD_IMAGE_ERROR);
export const deleteImage = makeApiActionCreator(api.deleteImage, DELETE_IMAGE_START, DELETE_IMAGE_SUCCESS, DELETE_IMAGE_ERROR);
