import * as api from '../api/reporting';
import { makeApiActionCreator } from './utils';

export const AGES_FETCH_START = 'AGES_FETCH_START';
export const AGES_FETCH_SUCCESS = 'AGES_FETCH_SUCCESS';
export const AGES_FETCH_ERROR = 'AGES_FETCH_ERROR';

export const EVENTS_FETCH_START = 'EVENTS_FETCH_START';
export const EVENTS_FETCH_SUCCESS = 'EVENTS_FETCH_SUCCESS';
export const EVENTS_FETCH_ERROR = 'EVENTS_FETCH_ERROR';

export const GENDERS_FETCH_START = 'GENDERS_FETCH_START';
export const GENDERS_FETCH_SUCCESS = 'GENDERS_FETCH_SUCCESS';
export const GENDERS_FETCH_ERROR = 'GENDERS_FETCH_ERROR';

export const TIMELINE_DATA_FETCH_START = 'TIMELINE_DATA_FETCH_START';
export const TIMELINE_DATA_FETCH_SUCCESS = 'TIMELINE_DATA_FETCH_SUCCESS';
export const TIMELINE_DATA_FETCH_ERROR = 'TIMELINE_DATA_FETCH_ERROR';

export const AGE_DATA_FETCH_START = 'AGE_DATA_FETCH_START';
export const AGE_DATA_FETCH_SUCCESS = 'AGE_DATA_FETCH_SUCCESS';
export const AGE_DATA_FETCH_ERROR = 'AGE_DATA_FETCH_ERROR';

export const GENDER_DATA_FETCH_START = 'GENDER_DATA_FETCH_START';
export const GENDER_DATA_FETCH_SUCCESS = 'GENDER_DATA_FETCH_SUCCESS';
export const GENDER_DATA_FETCH_ERROR = 'GENDER_DATA_FETCH_ERROR';

export const CHARACTER_SUBSCRIPTIONS_FETCH_START = 'CHARACTER_SUBSCRIPTIONS_FETCH_START';
export const CHARACTER_SUBSCRIPTIONS_FETCH_SUCCESS = 'CHARACTER_SUBSCRIPTIONS_FETCH_SUCCESS';
export const CHARACTER_SUBSCRIPTIONS_FETCH_ERROR = 'CHARACTER_SUBSCRIPTIONS_FETCH_ERROR';

export const fetchAges = makeApiActionCreator(api.getAges, AGES_FETCH_START, AGES_FETCH_SUCCESS, AGES_FETCH_ERROR);

export const fetchEvents = makeApiActionCreator(api.getActivityReportEvents, EVENTS_FETCH_START, EVENTS_FETCH_SUCCESS, EVENTS_FETCH_ERROR);

export const fetchGenders = makeApiActionCreator(api.getGenders, GENDERS_FETCH_START, GENDERS_FETCH_SUCCESS, GENDERS_FETCH_ERROR);

export const fetchTimelineData = makeApiActionCreator(api.getTimelineData, TIMELINE_DATA_FETCH_START, TIMELINE_DATA_FETCH_SUCCESS, TIMELINE_DATA_FETCH_ERROR);

export const fetchAgeData = makeApiActionCreator(api.getAgeData, AGE_DATA_FETCH_START, AGE_DATA_FETCH_SUCCESS, AGE_DATA_FETCH_ERROR);

export const fetchGenderData = makeApiActionCreator(api.getGenderData, GENDER_DATA_FETCH_START, GENDER_DATA_FETCH_SUCCESS, GENDER_DATA_FETCH_ERROR);

export const fetchCharacterSubscriptions = makeApiActionCreator(api.getRankingCharacterSubscriptions, CHARACTER_SUBSCRIPTIONS_FETCH_START, CHARACTER_SUBSCRIPTIONS_FETCH_SUCCESS, CHARACTER_SUBSCRIPTIONS_FETCH_ERROR);
