import { makeApiActionCreator } from './utils';
import * as scheduleEntryApi from '../api/scheduleEntry';

export const SCHEDULE_ENTRY_FETCH_START = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_FETCH_START';
export const SCHEDULE_ENTRY_FETCH_SUCCESS = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_FETCH_SUCCESS';
export const SCHEDULE_ENTRY_FETCH_ERROR = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_FETCH_ERROR';

export const SCHEDULE_ENTRY_PERSIST_START = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_PERSIST_START';
export const SCHEDULE_ENTRY_PERSIST_SUCCESS = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_PERSIST_SUCCESS';
export const SCHEDULE_ENTRY_PERSIST_ERROR = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_PERSIST_ERROR';

export const SCHEDULE_ENTRY_DELETE_START = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_DELETE_START';
export const SCHEDULE_ENTRY_DELETE_SUCCESS = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_DELETE_SUCCESS';
export const SCHEDULE_ENTRY_DELETE_ERROR = 'SCHEDULE_ENTRY/SCHEDULE_ENTRY_DELETE_ERROR';

export const SCHEDULE_ENTRIES_DELETE_START = 'SCHEDULE_ENTRY/SCHEDULE_ENTRIES_DELETE_START';
export const SCHEDULE_ENTRIES_DELETE_SUCCESS = 'SCHEDULE_ENTRY/SCHEDULE_ENTRIES_DELETE_SUCCESS';
export const SCHEDULE_ENTRIES_DELETE_ERROR = 'SCHEDULE_ENTRY/SCHEDULE_ENTRIES_DELETE_ERROR';

export const fetchScheduleEntry = makeApiActionCreator(scheduleEntryApi.fetchScheduleEntry, SCHEDULE_ENTRY_FETCH_START, SCHEDULE_ENTRY_FETCH_SUCCESS, SCHEDULE_ENTRY_FETCH_ERROR);
export const persistScheduleEntry = makeApiActionCreator(scheduleEntryApi.persistScheduleEntry, SCHEDULE_ENTRY_PERSIST_START, SCHEDULE_ENTRY_PERSIST_SUCCESS, SCHEDULE_ENTRY_PERSIST_ERROR);
export const deleteScheduleEntries = makeApiActionCreator(scheduleEntryApi.deleteScheduleEntries, SCHEDULE_ENTRIES_DELETE_START, SCHEDULE_ENTRIES_DELETE_SUCCESS, SCHEDULE_ENTRIES_DELETE_ERROR);
export const deleteScheduleEntry = makeApiActionCreator(scheduleEntryApi.deleteScheduleEntry, SCHEDULE_ENTRY_DELETE_START, SCHEDULE_ENTRY_DELETE_SUCCESS, SCHEDULE_ENTRY_DELETE_ERROR);
