import * as api from '../api/series';
import { makeApiActionCreator } from './utils';

export const SERIES_ENTRIES_SEARCH_START = 'SERIES/SERIES_ENTRIES_SEARCH_START';
export const SERIES_ENTRIES_SEARCH_SUCCESS = 'SERIES/SERIES_ENTRIES_SEARCH_SUCCESS';
export const SERIES_ENTRIES_SEARCH_ERROR = 'SERIES/SERIES_ENTRIES_SEARCH_ERROR';

export const SERIES_ENTRIES_FETCH_START = 'SERIES/SERIES_ENTRIES_FETCH_START';
export const SERIES_ENTRIES_FETCH_SUCCESS = 'SERIES/SERIES_ENTRIES_FETCH_SUCCESS';
export const SERIES_ENTRIES_FETCH_ERROR = 'SERIES/SERIES_ENTRIES_FETCH_ERROR';

export const SERIES_ENTRY_FETCH_START = 'SERIES/SERIES_ENTRY_FETCH_START';
export const SERIES_ENTRY_FETCH_SUCCESS = 'SERIES/SERIES_ENTRY_FETCH_SUCCESS';
export const SERIES_ENTRY_FETCH_ERROR = 'SERIES/SERIES_ENTRY_FETCH_ERROR';

export const SERIES_ENTRY_PERSIST_START = 'SERIES/SERIES_ENTRY_PERSIST_START';
export const SERIES_ENTRY_PERSIST_SUCCESS = 'SERIES/SERIES_ENTRY_PERSIST_SUCCESS';
export const SERIES_ENTRY_PERSIST_ERROR = 'SERIES/SERIES_ENTRY_PERSIST_ERROR';

export const SERIES_ENTRY_DELETE_START = 'SERIES/SERIES_ENTRY_DELETE_START';
export const SERIES_ENTRY_DELETE_SUCCESS = 'SERIES/SERIES_ENTRY_DELETE_SUCCESS';
export const SERIES_ENTRY_DELETE_ERROR = 'SERIES/SERIES_ENTRY_DELETE_ERROR';

export const SERIES_ENTRIES_DELETE_START = 'SERIES/SERIES_ENTRIES_DELETE_START';
export const SERIES_ENTRIES_DELETE_SUCCESS = 'SERIES/SERIES_ENTRIES_DELETE_SUCCESS';
export const SERIES_ENTRIES_DELETE_ERROR = 'SERIES/SERIES_ENTRIES_DELETE_ERROR';

export const SERIES_ENTRY_SEASONS_FETCH_START = 'SERIES/SERIES_ENTRY_SEASONS_FETCH_START';
export const SERIES_ENTRY_SEASONS_FETCH_SUCCESS = 'SERIES/SERIES_ENTRY_SEASONS_FETCH_SUCCESS';
export const SERIES_ENTRY_SEASONS_FETCH_ERROR = 'SERIES/SERIES_ENTRY_SEASONS_FETCH_ERROR';

export const SEASONS_SEARCH_START = 'SERIES/SEASONS_SEARCH_START';
export const SEASONS_SEARCH_SUCCESS = 'SERIES/SEASONS_SEARCH_SUCCESS';
export const SEASONS_SEARCH_ERROR = 'SERIES/SEASONS_SEARCH_ERROR';

export const fetchSeriesEntrySeasons = makeApiActionCreator(api.fetchSeriesEntrySeasons, SERIES_ENTRY_SEASONS_FETCH_START, SERIES_ENTRY_SEASONS_FETCH_SUCCESS, SERIES_ENTRY_SEASONS_FETCH_ERROR);
export const fetchSeriesEntries = makeApiActionCreator(api.fetchSeriesEntries, SERIES_ENTRIES_FETCH_START, SERIES_ENTRIES_FETCH_SUCCESS, SERIES_ENTRIES_FETCH_ERROR);
export const fetchSeriesEntry = makeApiActionCreator(api.fetchSeriesEntry, SERIES_ENTRY_FETCH_START, SERIES_ENTRY_FETCH_SUCCESS, SERIES_ENTRY_FETCH_ERROR);
export const persistSeriesEntry = makeApiActionCreator(api.persistSeriesEntry, SERIES_ENTRY_PERSIST_START, SERIES_ENTRY_PERSIST_SUCCESS, SERIES_ENTRY_PERSIST_ERROR);
export const deleteSeriesEntries = makeApiActionCreator(api.deleteSeriesEntries, SERIES_ENTRIES_DELETE_START, SERIES_ENTRIES_DELETE_SUCCESS, SERIES_ENTRIES_DELETE_ERROR);
export const deleteSeriesEntry = makeApiActionCreator(api.deleteSeriesEntry, SERIES_ENTRY_DELETE_START, SERIES_ENTRY_DELETE_SUCCESS, SERIES_ENTRY_DELETE_ERROR);
export const searchSeriesEntries = makeApiActionCreator(api.searchSeriesEntries, SERIES_ENTRIES_SEARCH_START, SERIES_ENTRIES_SEARCH_SUCCESS, SERIES_ENTRIES_SEARCH_ERROR);
export const searchSeasons = makeApiActionCreator(api.searchSeasons, SEASONS_SEARCH_START, SEASONS_SEARCH_SUCCESS, SEASONS_SEARCH_ERROR);
