// import * as api from '../api/contentProducer';
// import { makeApiActionCreator } from './utils';

export const SERIES_ENRTY_SEARCH_START = 'SERIES/SERIES_ENRTY_SEARCH_START';
export const SERIES_ENRTY_SEARCH_SUCCESS = 'SERIES/SERIES_ENRTY_SEARCH_SUCCESS';
export const SERIES_ENRTY_SEARCH_ERROR = 'SERIES/SERIES_ENRTY_SEARCH_ERROR';

export const SERIES_ENTRIES_FETCH_START = 'SERIES/SERIES_ENTRIES_FETCH_START';
export const SERIES_ENTRIES_FETCH_SUCCESS = 'SERIES/SERIES_ENTRIES_FETCH_SUCCESS';
export const SERIES_ENTRIES_FETCH_ERROR = 'SERIES/SERIES_ENTRIES_FETCH_ERROR';

export const SERIES_ENRTY_FETCH_START = 'SERIES/SERIES_ENRTY_FETCH_START';
export const SERIES_ENRTY_FETCH_SUCCESS = 'SERIES/SERIES_ENRTY_FETCH_SUCCESS';
export const SERIES_ENRTY_FETCH_ERROR = 'SERIES/SERIES_ENRTY_FETCH_ERROR';

export const SERIES_ENRTY_PERSIST_START = 'SERIES/SERIES_ENRTY_PERSIST_START';
export const SERIES_ENRTY_PERSIST_SUCCESS = 'SERIES/SERIES_ENRTY_PERSIST_SUCCESS';
export const SERIES_ENRTY_PERSIST_ERROR = 'SERIES/SERIES_ENRTY_PERSIST_ERROR';

export const SERIES_ENRTY_DELETE_START = 'SERIES/SERIES_ENRTY_DELETE_START';
export const SERIES_ENRTY_DELETE_SUCCESS = 'SERIES/SERIES_ENRTY_DELETE_SUCCESS';
export const SERIES_ENRTY_DELETE_ERROR = 'SERIES/SERIES_ENRTY_DELETE_ERROR';

export const SERIES_ENTRIES_DELETE_START = 'SERIES/SERIES_ENTRIES_DELETE_START';
export const SERIES_ENTRIES_DELETE_SUCCESS = 'SERIES/SERIES_ENTRIES_DELETE_SUCCESS';
export const SERIES_ENTRIES_DELETE_ERROR = 'SERIES/SERIES_ENTRIES_DELETE_ERROR';

// export const fetchSeriesEntryUsers = makeApiActionCreator(api.fetchSeriesEntryUsers, SERIES_ENRTY_USERS_FETCH_START, SERIES_ENRTY_USERS_FETCH_SUCCESS, SERIES_ENRTY_USERS_FETCH_ERROR);
// export const fetchSeriesEntries = makeApiActionCreator(api.fetchSeriesEntries, SERIES_ENTRIES_FETCH_START, SERIES_ENTRIES_FETCH_SUCCESS, SERIES_ENTRIES_FETCH_ERROR);
// export const fetchSeriesEntry = makeApiActionCreator(api.fetchSeriesEntry, SERIES_ENRTY_FETCH_START, SERIES_ENRTY_FETCH_SUCCESS, SERIES_ENRTY_FETCH_ERROR);
// export const persistSeriesEntry = makeApiActionCreator(api.persistSeriesEntry, SERIES_ENRTY_PERSIST_START, SERIES_ENRTY_PERSIST_SUCCESS, SERIES_ENRTY_PERSIST_ERROR);
// export const deleteSeriesEntries = makeApiActionCreator(api.deleteSeriesEntries, SERIES_ENTRIES_DELETE_START, SERIES_ENTRIES_DELETE_SUCCESS, SERIES_ENTRIES_DELETE_ERROR);
// export const deleteSeriesEntry = makeApiActionCreator(api.deleteSeriesEntry, SERIES_ENRTY_DELETE_START, SERIES_ENRTY_DELETE_SUCCESS, SERIES_ENRTY_DELETE_ERROR);
// export const searchSeriesEntries = makeApiActionCreator(api.searchSeriesEntries, SERIES_ENRTY_SEARCH_START, SERIES_ENRTY_SEARCH_SUCCESS, SERIES_ENRTY_SEARCH_ERROR);
