import * as api from '../api/shop';
import { makeApiActionCreator } from './utils';

export const SHOP_SEARCH_START = 'SHOP/SHOP_SEARCH_START';
export const SHOP_SEARCH_SUCCESS = 'SHOP/SHOP_SEARCH_SUCCESS';
export const SHOP_SEARCH_ERROR = 'SHOP/SHOP_SEARCH_ERROR';

export const SHOPS_FETCH_START = 'SHOP/SHOPS_FETCH_START';
export const SHOPS_FETCH_SUCCESS = 'SHOP/SHOPS_FETCH_SUCCESS';
export const SHOPS_FETCH_ERROR = 'SHOP/SHOPS_FETCH_ERROR';

export const SHOP_FETCH_START = 'SHOP/SHOP_FETCH_START';
export const SHOP_FETCH_SUCCESS = 'SHOP/SHOP_FETCH_SUCCESS';
export const SHOP_FETCH_ERROR = 'SHOP/SHOP_FETCH_ERROR';

export const SHOP_DELETE_START = 'SHOP/SHOP_DELETE_START';
export const SHOP_DELETE_SUCCESS = 'SHOP/SHOP_DELETE_SUCCESS';
export const SHOP_DELETE_ERROR = 'SHOP/SHOP_DELETE_ERROR';

export const SHOPS_DELETE_START = 'SHOP/SHOPS_DELETE_START';
export const SHOPS_DELETE_SUCCESS = 'SHOP/SHOPS_DELETE_SUCCESS';
export const SHOPS_DELETE_ERROR = 'SHOP/SHOPS_DELETE_ERROR';

export const SHOP_PERSIST_START = 'SHOP/SHOP_PERSIST_START';
export const SHOP_PERSIST_SUCCESS = 'SHOP/SHOP_PERSIST_SUCCESS';
export const SHOP_PERSIST_ERROR = 'SHOP/SHOP_PERSIST_ERROR';

export const UPLOAD_LOGO_IMAGE_START = 'SHOP/UPLOAD_LOGO_IMAGE_START';
export const UPLOAD_LOGO_IMAGE_SUCCESS = 'SHOP/UPLOAD_LOGO_IMAGE_SUCCESS';
export const UPLOAD_LOGO_IMAGE_ERROR = 'SHOP/UPLOAD_LOGO_IMAGE_ERROR';

export const UPLOAD_FACE_IMAGE_START = 'SHOP/UPLOAD_FACE_IMAGE_START';
export const UPLOAD_FACE_IMAGE_SUCCESS = 'SHOP/UPLOAD_FACE_IMAGE_SUCCESS';
export const UPLOAD_FACE_IMAGE_ERROR = 'SHOP/UPLOAD_FACE_IMAGE_ERROR';

export const DELETE_LOGO_IMAGE_START = 'SHOP/DELETE_LOGO_IMAGE_START';
export const DELETE_LOGO_IMAGE_SUCCESS = 'SHOP/DELETE_LOGO_IMAGE_SUCCESS';
export const DELETE_LOGO_IMAGE_ERROR = 'SHOP/DELETE_LOGO_IMAGE_ERROR';

export const deleteLogoImage = makeApiActionCreator(api.deleteLogoImage, DELETE_LOGO_IMAGE_START, DELETE_LOGO_IMAGE_SUCCESS, DELETE_LOGO_IMAGE_ERROR);
export const deleteShops = makeApiActionCreator(api.deleteShops, SHOPS_DELETE_START, SHOPS_DELETE_SUCCESS, SHOPS_DELETE_ERROR);
export const deleteShop = makeApiActionCreator(api.deleteShop, SHOP_DELETE_START, SHOP_DELETE_SUCCESS, SHOP_DELETE_ERROR);
export const fetchShops = makeApiActionCreator(api.fetchShops, SHOPS_FETCH_START, SHOPS_FETCH_SUCCESS, SHOPS_FETCH_ERROR);
export const fetchShop = makeApiActionCreator(api.fetchShop, SHOP_FETCH_START, SHOP_FETCH_SUCCESS, SHOP_FETCH_ERROR);
export const persistShop = makeApiActionCreator(api.persistShop, SHOP_PERSIST_START, SHOP_PERSIST_SUCCESS, SHOP_PERSIST_ERROR);
export const searchShops = makeApiActionCreator(api.searchShops, SHOP_SEARCH_START, SHOP_SEARCH_SUCCESS, SHOP_SEARCH_ERROR);
export const uploadLogoImage = makeApiActionCreator(api.uploadLogoImage, UPLOAD_LOGO_IMAGE_START, UPLOAD_LOGO_IMAGE_SUCCESS, UPLOAD_LOGO_IMAGE_ERROR);
