import { makeApiActionCreator } from './utils';
import * as api from '../api/topic';

export const CROP_TOPICS_FETCH_START = 'TOPIC/CROP_TOPICS_FETCH_START';
export const CROP_TOPICS_FETCH_SUCCESS = 'TOPIC/CROP_TOPICS_FETCH_SUCCESS';
export const CROP_TOPICS_FETCH_ERROR = 'TOPIC/CROP_TOPICS_FETCH_ERROR';

export const DELETE_BACKGROUND_IMAGE_START = 'TOPIC/DELETE_BACKGROUND_IMAGE_START';
export const DELETE_BACKGROUND_IMAGE_SUCCESS = 'TOPIC/DELETE_BACKGROUND_IMAGE_SUCCESS';
export const DELETE_BACKGROUND_IMAGE_ERROR = 'TOPIC/DELETE_BACKGROUND_IMAGE_ERROR';

export const DELETE_THUMB_IMAGE_START = 'TOPIC/DELETE_THUMB_IMAGE_START';
export const DELETE_THUMB_IMAGE_SUCCESS = 'TOPIC/DELETE_THUMB_IMAGE_SUCCESS';
export const DELETE_THUMB_IMAGE_ERROR = 'TOPIC/DELETE_THUMB_IMAGE_ERROR';

export const TOPIC_DELETE_START = 'TOPIC/TOPIC_DELETE_START';
export const TOPIC_DELETE_SUCCESS = 'TOPIC/TOPIC_DELETE_SUCCESS';
export const TOPIC_DELETE_ERROR = 'TOPIC/TOPIC_DELETE_ERROR';

export const TOPICS_DELETE_START = 'TOPIC/TOPICS_DELETE_START';
export const TOPICS_DELETE_SUCCESS = 'TOPIC/TOPICS_DELETE_SUCCESS';
export const TOPICS_DELETE_ERROR = 'TOPIC/TOPICS_DELETE_ERROR';

export const TOPIC_FETCH_START = 'TOPIC/TOPIC_FETCH_START';
export const TOPIC_FETCH_SUCCESS = 'TOPIC/TOPIC_FETCH_SUCCESS';
export const TOPIC_FETCH_ERROR = 'TOPIC/TOPIC_FETCH_ERROR';

export const TOPICS_FETCH_START = 'TOPIC/TOPICS_FETCH_START';
export const TOPICS_FETCH_SUCCESS = 'TOPIC/TOPICS_FETCH_SUCCESS';
export const TOPICS_FETCH_ERROR = 'TOPIC/TOPICS_FETCH_ERROR';

export const TOPICS_SEARCH_START = 'TOPIC/TOPICS_SEARCH_START';
export const TOPICS_SEARCH_SUCCESS = 'TOPIC/TOPICS_SEARCH_SUCCESS';
export const TOPICS_SEARCH_ERROR = 'TOPIC/TOPICS_SEARCH_ERROR';

export const TOPIC_PERSIST_START = 'TOPIC/TOPIC_PERSIST_START';
export const TOPIC_PERSIST_SUCCESS = 'TOPIC/TOPIC_PERSIST_SUCCESS';
export const TOPIC_PERSIST_ERROR = 'TOPIC/TOPIC_PERSIST_ERROR';

export const UPLOAD_BACKGROUND_IMAGE_START = 'TOPIC/UPLOAD_BACKGROUND_IMAGE_START';
export const UPLOAD_BACKGROUND_IMAGE_SUCCESS = 'TOPIC/UPLOAD_BACKGROUND_IMAGE_SUCCESS';
export const UPLOAD_BACKGROUND_IMAGE_ERROR = 'TOPIC/UPLOAD_BACKGROUND_IMAGE_ERROR';

export const UPLOAD_THUMB_IMAGE_START = 'TOPIC/UPLOAD_THUMB_IMAGE_START';
export const UPLOAD_THUMB_IMAGE_SUCCESS = 'TOPIC/UPLOAD_THUMB_IMAGE_SUCCESS';
export const UPLOAD_THUMB_IMAGE_ERROR = 'TOPIC/UPLOAD_THUMB_IMAGE_ERROR';

export const deleteBackgroundImage = makeApiActionCreator(api.deleteBackgroundImage, DELETE_BACKGROUND_IMAGE_START, DELETE_BACKGROUND_IMAGE_SUCCESS, DELETE_BACKGROUND_IMAGE_SUCCESS);
export const deleteThumbImage = makeApiActionCreator(api.deleteThumbImage, DELETE_THUMB_IMAGE_START, DELETE_THUMB_IMAGE_SUCCESS, DELETE_THUMB_IMAGE_ERROR);
export const deleteTopic = makeApiActionCreator(api.deleteTopic, TOPIC_DELETE_START, TOPIC_DELETE_SUCCESS, TOPIC_DELETE_ERROR);
export const deleteTopics = makeApiActionCreator(api.deleteTopics, TOPICS_DELETE_START, TOPICS_DELETE_SUCCESS, TOPICS_DELETE_ERROR);
export const fetchCropTopics = makeApiActionCreator(api.fetchCropTopics, CROP_TOPICS_FETCH_START, CROP_TOPICS_FETCH_SUCCESS, CROP_TOPICS_FETCH_ERROR);
export const fetchTopic = makeApiActionCreator(api.fetchTopic, TOPIC_FETCH_START, TOPIC_FETCH_SUCCESS, TOPIC_FETCH_ERROR);
export const fetchTopics = makeApiActionCreator(api.fetchTopics, TOPICS_FETCH_START, TOPICS_FETCH_SUCCESS, TOPICS_FETCH_ERROR);
export const persistTopic = makeApiActionCreator(api.persistTopic, TOPIC_PERSIST_START, TOPIC_PERSIST_SUCCESS, TOPIC_PERSIST_ERROR);
export const searchTopics = makeApiActionCreator(api.searchTopics, TOPICS_SEARCH_START, TOPICS_SEARCH_SUCCESS, TOPICS_SEARCH_ERROR);
export const uploadThumbImage = makeApiActionCreator(api.uploadThumbImage, UPLOAD_THUMB_IMAGE_START, UPLOAD_THUMB_IMAGE_SUCCESS, UPLOAD_THUMB_IMAGE_ERROR);
export const uploadBackgroundImage = makeApiActionCreator(api.uploadBackgroundImage, UPLOAD_BACKGROUND_IMAGE_START, UPLOAD_BACKGROUND_IMAGE_SUCCESS, UPLOAD_BACKGROUND_IMAGE_ERROR);
