import * as api from '../api/tvGuide';
import { makeApiActionCreator } from './utils';

export const TV_GUIDE_ENTRIES_FETCH_START = 'TV_GUIDE/TV_GUIDE_ENTRIES_FETCH_START';
export const TV_GUIDE_ENTRIES_FETCH_SUCCESS = 'TV_GUIDE/TV_GUIDE_ENTRIES_FETCH_SUCCESS';
export const TV_GUIDE_ENTRIES_FETCH_ERROR = 'TV_GUIDE/TV_GUIDE_ENTRIES_FETCH_ERROR';

export const TV_GUIDE_ENTRY_FETCH_START = 'TV_GUIDE/TV_GUIDE_ENTRY_FETCH_START';
export const TV_GUIDE_ENTRY_FETCH_SUCCESS = 'TV_GUIDE/TV_GUIDE_ENTRY_FETCH_SUCCESS';
export const TV_GUIDE_ENTRY_FETCH_ERROR = 'TV_GUIDE/TV_GUIDE_ENTRY_FETCH_ERROR';

export const TV_GUIDE_ENTRY_PERSIST_START = 'TV_GUIDE/TV_GUIDE_ENTRY_PERSIST_START';
export const TV_GUIDE_ENTRY_PERSIST_SUCCESS = 'TV_GUIDE/TV_GUIDE_ENTRY_PERSIST_SUCCESS';
export const TV_GUIDE_ENTRY_PERSIST_ERROR = 'TV_GUIDE/TV_GUIDE_ENTRY_PERSIST_ERROR';

export const TV_GUIDE_ENTRY_DELETE_START = 'TV_GUIDE/TV_GUIDE_ENTRY_DELETE_START';
export const TV_GUIDE_ENTRY_DELETE_SUCCESS = 'TV_GUIDE/TV_GUIDE_ENTRY_DELETE_SUCCESS';
export const TV_GUIDE_ENTRY_DELETE_ERROR = 'TV_GUIDE/TV_GUIDE_ENTRY_DELETE_ERROR';

export const TV_GUIDE_ENTRIES_DELETE_START = 'TV_GUIDE/TV_GUIDE_ENTRIES_DELETE_START';
export const TV_GUIDE_ENTRIES_DELETE_SUCCESS = 'TV_GUIDE/TV_GUIDE_ENTRIES_DELETE_SUCCESS';
export const TV_GUIDE_ENTRIES_DELETE_ERROR = 'TV_GUIDE/TV_GUIDE_ENTRIES_DELETE_ERROR';

export const fetchTvGuideEntries = makeApiActionCreator(api.fetchTvGuideEntries, TV_GUIDE_ENTRIES_FETCH_START, TV_GUIDE_ENTRIES_FETCH_SUCCESS, TV_GUIDE_ENTRIES_FETCH_ERROR);
export const fetchTvGuideEntry = makeApiActionCreator(api.fetchTvGuideEntry, TV_GUIDE_ENTRY_FETCH_START, TV_GUIDE_ENTRY_FETCH_SUCCESS, TV_GUIDE_ENTRY_FETCH_ERROR);
export const deleteTvGuideEntries = makeApiActionCreator(api.deleteTvGuideEntries, TV_GUIDE_ENTRIES_DELETE_START, TV_GUIDE_ENTRIES_DELETE_SUCCESS, TV_GUIDE_ENTRIES_DELETE_ERROR);
export const deleteTvGuideEntry = makeApiActionCreator(api.deleteTvGuideEntry, TV_GUIDE_ENTRY_DELETE_START, TV_GUIDE_ENTRY_DELETE_SUCCESS, TV_GUIDE_ENTRY_DELETE_ERROR);
export const persistTvGuideEntry = makeApiActionCreator(api.persistTvGuideEntry, TV_GUIDE_ENTRY_PERSIST_START, TV_GUIDE_ENTRY_PERSIST_SUCCESS, TV_GUIDE_ENTRY_PERSIST_ERROR);
