export const AUTHENTICATE = 'AUTHENTICATE';

export const CREATE_MEDIA_START_WIZARD = 'CREATE_MEDIA_START_WIZARD';
export const CREATE_MEDIA_SELECT_TAB = 'CREATE_MEDIA_SELECT_TAB';
export const CREATE_MEDIA_SELECT_MEDIA_TYPE = 'CREATE_MEDIA_SELECT_MEDIA_TYPE';
export const CREATE_MEDIA_CANCEL_WIZARD = 'CREATE_MEDIA_CANCEL_WIZARD';

export const CREATE_MEDIA_START = 'CREATE_MEDIA_START';
export const CREATE_MEDIA_SUCCESS = 'CREATE_MEDIA_SUCCESS';
export const CREATE_MEDIA_ERROR = 'CREATE_MEDIA_ERROR';

export const PROCESS_MEDIA_START = 'PROCESS_MEDIA_START';
export const PROCESS_MEDIA_SUCCESS = 'PROCESS_MEDIA_SUCCESS';
export const PROCESS_MEDIA_ERROR = 'PROCESS_MEDIA_ERROR';

export const UPLOAD_FILE_START = 'MEDIA_UPLOAD_FILE_START';
export const UPLOAD_FILE_SUCCESS = 'MEDIA_UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'MEDIA_UPLOAD_FILE_ERROR';
export const UPLOAD_FILE_PROGRESS = 'MEDIA_UPLOAD_FILE_PROGRESS';

export const MODAL_OPEN_LOGIN = 'MODAL_OPEN_LOGIN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
