export const BRAND_SUBSCRIPTIONS = 'BRAND_SUBSCRIPTIONS';
export const CONVERSION = 'CONVERSION';
export const PRODUCT_BUYS = 'PRODUCT_BUYS';
export const PRODUCT_IMPRESSIONS = 'PRODUCT_IMPRESSIONS';
export const PRODUCT_VIEWS = 'PRODUCT_VIEWS';
export const TAGGED_PRODUCTS = 'TAGGED_PRODUCTS';
